- config/initializers/inflections.rb
- spec/features/crops/inflections_spec.rb
> Add inflections for irregular plural crop names

- app/views/crops/_find_seeds.html.haml
- app/views/crops/_harvests.html.haml
- app/views/crops/_plantings.html.haml
- app/views/crops/show.html.haml
- spec/features/crops/crop_detail_page_spec.rb
> Add SEO-friendly language to the crop detail page

- app/views/crops/_index_card.html.haml
- app/views/members/_avatar.html.haml
- app/views/photos/index.html.haml
- app/views/photos/new.html.haml
- app/views/photos/show.html.haml
- app/views/plantings/_thumbnail.html.haml
> got rid of all img-rounded classes

- app/assets/stylesheets/overrides.css.less
- app/views/crops/_thumbnail.html.haml
Blergh. My what-I-thought-were-minor CSS tweaks last night screwed things up.
Fixes #651.
As this is affecting the homepage right now, if I don't see a response to this in say ~12 hours I will self-merge and push to prod.
> Fixed CSS errors with text wrapping

- app/controllers/follows_controller.rb
- app/models/ability.rb
- app/views/members/show.html.haml
- spec/features/following_spec.rb
- spec/features/member_profile_spec.rb
Fixes #638.
Or at least, sorta-kinda fixes it as much as I'm going to.  Copypasta from my comments over there:
I've added the checks to the controller but I don't think we can realistically prevent people from doing what thorfinn did in the link above (i.e. using web developer tools to hack the page's HTML and intentionally follow himself). OTOH, if they want to go to all that trouble to follow themselves, there's no real harm done, so I don't think it's a real problem.
> Tidied up authorization around follows

- app/controllers/crops_controller.rb
- config/environments/staging.rb
- db/schema.rb
- spec/features/crops/crop_wranglers_spec.rb
Fixes [666](https://github.com/Growstuff/growstuff/issues/666#issuecomment-71002122)
> Sci names permitted params

- app/controllers/crops_controller.rb
- config/environments/staging.rb
- db/schema.rb
- spec/features/crops/crop_wranglers_spec.rb
Need to deal with weird schema changes before merging
Reverts Growstuff/growstuff#669
> Revert "Sci names permitted params"

- app/controllers/follows_controller.rb
- spec/features/following_spec.rb
See discussion at http://talk.growstuff.org/t/please-test-footer-height-authorisation-on-follows
> Fix the 500 server error when you try to follow another user

- app/controllers/photos_controller.rb
- app/models/garden.rb
- app/models/photo.rb
- app/views/gardens/show.html.haml
- app/views/members/_gardens.html.haml
- db/migrate/20150127043022_add_gardens_photos_table.rb
- db/schema.rb
- spec/controllers/photos_controller_spec.rb
- spec/models/garden_spec.rb
- spec/models/photo_spec.rb
This should get the ability to add photos to gardens. The photos will then display both on the garden detail page and in the garden tabs on the member page.
Fixes #600
> Garden photos

- app/controllers/harvests_controller.rb
- spec/controllers/harvests_controller_spec.rb
owner.name doesn't exist, but owner.login_name does
This is making the harvest CSV error out when you try to see it. I'm not really sure what kind of test I'd add for this though.
Fixes #681
> fixing harvest csv so it doesn't error

- app/models/crop.rb
- db/schema.rb
Fix for tests that were failing if you didn't have elasticsearch running on your dev machine.
> Fixed test failure if elasticsearch isn't present in test env

- app/controllers/seeds_controller.rb
- app/models/garden.rb
- app/models/harvest.rb
- app/models/planting.rb
- app/models/product.rb
- app/models/seed.rb
- app/views/seeds/_days_until_maturity.html.haml
- app/views/seeds/_form.html.haml
- app/views/seeds/show.html.haml
- db/migrate/20150124110540_add_properties_to_seeds.rb
- db/schema.rb
- spec/factories/seeds.rb
- spec/features/seeds/adding_seeds_spec.rb
- spec/features/seeds/misc_seeds_spec.rb
- spec/models/seed_spec.rb
- spec/rails_helper.rb
Fixes #493 
Fixes #523 
Fixes #614
> New seed properties: days until maturity, organic, GMO, heirloom

- CONTRIBUTORS.md
- app/controllers/members_controller.rb
- app/models/member.rb
- app/views/members/index.html.haml
- spec/features/members_list_spec.rb
I've mostly imitated the crops sort thing.
Not quite sure how to write automated tests for this, if any. I'd appreciate help regarding that.
Fixes #550
> Functionality to sort members by recently joined : Issue #550

- app/controllers/crops_controller.rb
fixing issue with 1)paginating crop search and 2)crop name autocomplete
> fixing issue with 1)paginating crop search and 2)crop name autocomplete

- config/routes.rb
Making the CMS admin path change @skud requested in previous CMS-related PR
> move cms admin to /admin/cms at skud's request

- app/assets/stylesheets/overrides.css.less
- app/views/layouts/_footer.html.haml
As @skud requested here: http://talk.growstuff.org/t/please-test-cms/231/2?u=maco
> change footer section names to generic footer1, footer2, footer3

- app/views/crops/_find_seeds.html.haml
- app/views/crops/_form.html.haml
- app/views/crops/_harvests.html.haml
- app/views/crops/_plantings.html.haml
- app/views/crops/edit.html.haml
- spec/features/crops/request_new_crop_spec.rb
As per the list of outstanding problems at http://talk.growstuff.org/t/please-test-requesting-new-crops-new-seed-attributes/223/17
I'm working through them and pushing them to this branch as I do so.
> Improvements to crop requests

- app/models/crop.rb
- app/views/crops/_approval_status_message.html.haml
- app/views/notifier/crop_request_approved.html.haml
- app/views/notifier/crop_request_rejected.html.haml
- app/views/notifier/new_crop_request.html.haml
- spec/models/crop_spec.rb
http://talk.growstuff.org/t/please-test-requesting-new-crops-new-seed-attributes/223/17 asks for the notifications to be made a little friendlier and include the reject reason in the email beyond just the word "other"
> Crop accept/reject notification improvements

- app/views/gardens/index.html.haml
- spec/features/gardens_spec.rb
Added "current" scope to plantings on gardens/index view and added test to features/garden_spec file
Fixes #610
> resolved issue-610 to display only active planting

- app/views/photos/show.html.haml
- spec/features/photos/show_photo_spec.rb
- spec/views/photos/show.html.haml_spec.rb
> Linkbacks in photo view page to harvest and gardens

- app/controllers/photos_controller.rb
Link to Issue: https://github.com/Growstuff/growstuff/issues/713
I simply added a flash message to the destroy action to the photos controller
> Issue #713:  Added flash message when photos deleted

- app/views/layouts/_meta.html.haml
added image to meta partial (issue #733)
> added growstuff-apple-touch-icon-precomposed.png to meta partial

- spec/features/admin/account_types_spec.rb
- spec/features/admin/forums_spec.rb
- spec/features/admin/products.rb
- spec/features/cms_spec.rb
- spec/features/crops/alternate_name_spec.rb
- spec/features/crops/request_new_crop_spec.rb
- spec/features/harvests/harvesting_a_crop_spec.rb
- spec/features/photos/show_photo_spec.rb
- spec/features/plantings/planting_a_crop_spec.rb
- spec/features/scientific_name_spec.rb
- spec/features/seeds/adding_seeds_spec.rb
- spec/features/seeds/misc_seeds_spec.rb
Refactor spec by changing before(:each) into let as requested in #503 
@pozorvlak
> Refactor spec tests

- spec/helpers/notifications_helper_spec.rb
Change before(:each) into let in spec/helpers as requested in #503
> Refactor spec/helpers

- CONTRIBUTORS.md
- app/views/harvests/_form.html.haml
#736 I got @maccath's commits and added it to an updated branch for her work to be merged.
@pozorvlak
> Add placeholder to harvest screen's plant part select box made by maccath

- app/helpers/crops_helper.rb
- app/views/crops/show.html.haml
- spec/features/crops/crop_detail_page_spec.rb
Hi,
To answer issue #549, I added a simple feature wherein the crop page shows whether a user has seeds for that crop or none.
> Added feature and test for request #549

- app/views/gardens/index.html.haml
- spec/views/gardens/index.html.haml_spec.rb
Added 'current' scope on gardens/index view and added accompanying view test
Fixes #610
> resolved issue #610 to show only current plantings 

- spec/support/controller_macros.rb
- spec/support/elasticsearch_helpers.rb
Changed before(:each) into before as requested in #503
> Refactor spec/support

- CONTRIBUTORS.md
- app/helpers/plantings_helper.rb
- app/views/crops/_plantings.html.haml
- spec/helpers/plantings_helper_spec.rb
Quantity and planted_from are not required
to add a planting. This change handles
the cases where one or both attributes are
missing.
Fixes #633
> Added Helper for See Who's Planted Link Text

- spec/models/ability_spec.rb
- spec/models/account_spec.rb
- spec/models/comment_spec.rb
- spec/models/crop_spec.rb
- spec/models/forum_spec.rb
- spec/models/garden_spec.rb
- spec/models/harvest_spec.rb
- spec/models/member_spec.rb
- spec/models/notification_spec.rb
- spec/models/order_item_spec.rb
- spec/models/planting_spec.rb
- spec/models/post_spec.rb
- spec/models/scientific_name_spec.rb
- spec/models/seed_spec.rb
Changed before(:each) into let as requested in #503 .
> Refactor spec/models

- app/views/layouts/_header.html.haml
- spec/features/following_spec.rb
- spec/views/layouts/_header_spec.rb
Reopened https://github.com/Growstuff/growstuff/pull/752 and made my code cleaner.
@pozorvlak thanks!
> Redesigned the navbar

- Gemfile.lock
- app/views/harvests/index.html.haml
- app/views/plantings/index.html.haml
- app/views/seeds/index.html.haml
- spec/features/harvests/harvesting_a_crop_spec.rb
- spec/features/plantings/planting_a_crop_spec.rb
- spec/features/seeds/misc_seeds_spec.rb
Here's a screenshot:
All tests passed. Tell me if there's anything more needed to be done.
> Added link to owner's profile from seeds', plantings', and harvests' index page (Fixes #569)

- app/assets/javascripts/finish_planting.js.coffee
- app/models/planting.rb
- app/views/gardens/_thumbnail.html.haml
- app/views/home/_stats.html.haml
- spec/controllers/photos_controller_spec.rb
- spec/models/crop_spec.rb
- spec/models/forum_spec.rb
- spec/models/garden_spec.rb
- spec/models/member_spec.rb
- spec/models/photo_spec.rb
- spec/models/planting_spec.rb
- spec/models/post_spec.rb
- spec/models/seed_spec.rb
- vendor/gems/activemerchant-1.33.0/lib/support/ssl_verify.rb
> Replace the last few .count and .length calls with .size where possible

- Gemfile.lock
- app/models/crop.rb
- app/models/planting.rb
The homepage is currently really slow to load - nearly 2s on my machine. A lot of this is due to the inefficient way in which we're calculating the lists of interesting crops and plantings - we load everything into memory from the DB, and then loop over them in Ruby, emitting more queries for each object to find out if it's interesting. With some moderately dark ActiveRecord magic we can do all of this calculation in only two database queries, getting page load time down to around 0.8s - still not great, but much better than it was.
Before
---------
```
$ ab -n 20 http://127.0.0.1:8080/
This is ApacheBench, Version 2.3 <$Revision: 1638069 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/ …
```
> Speed up homepage by calculating "interesting" things more efficiently

- app/views/posts/_summary.html.haml
- spec/views/forums/index.html.haml_spec.rb
Reverts Growstuff/growstuff#790
> Revert "Fixing relative caching of post summary on homepage, fixed #789"

- app/models/crop.rb
- app/models/planting.rb
Previous merge breaks travis builds - reverting while we investigate.
This reverts commit fa50ff47bb105cd9bd18a67d0c77109d19d65bc8, reversing
changes made to 5b19d236d002cb13f511c06f6f31a55a4153e4b7.
Once fixed, please read https://www.kernel.org/pub/software/scm/git/docs/howto/revert-a-faulty-merge.html carefully to get it back in properly.
> Revert "Merge pull request #775 from pozorvlak/speed_up_homepage"

- app/views/seeds/index.csv.shaper
- app/views/seeds/index.rss.haml
Fix #677 by adding organic/GMO/heirloom to CSV and RSS
> Fix #677 by adding organic/GMO/heirloom to CSV and RSS

- app/views/layouts/_header.html.haml
- config/locales/en.yml
An example of internationalising a string, to make it clearer for future beginners looking at #658.
> Issue #658 i18n

- app/views/crops/_thumbnail.html.haml
Helping performance issues on CropsController#index by caching thumbnails. Needs careful checking that cache expires correctly when a new planting is added.
> Cache thumbnails

- spec/features/admin/account_types_spec.rb
Extra comments as per discussion on #810.
> Adding commentary to test for clarification of non-JS version

- app/controllers/plantings_controller.rb
> Fix bug #827 : Error in generating csv file for plantings with owner filter

- app/views/shared/_markdown_help.html.haml
- lib/haml/filters/growstuff_markdown.rb
- spec/lib/haml/filters/growstuff_markdown_spec.rb
> Quick links to members in markdown 

- app/models/crop.rb
- app/models/planting.rb
Fixes #840 
Before: Large number of queries
After - it's down to two (though we should probably add sane limits or find_in_batches so we don't have to grab *every* crop; and rely on some other random() behaviour)
```
Crop Load (2.4ms)  SELECT "crops".* FROM "crops"  WHERE "crops"."approval_status" = 'approved'  ORDER BY random()
Planting Load (1.0ms)  SELECT "plantings".* FROM "plantings"  WHERE "plantings"."crop_id" IN (239, 390, 80, 8, 292, 199, 227, 18, 78, 230, 307, 191, 13, 348, 340, 74, 366, 313, 54, 206, 172, 24, 335, 202, 61, 181, 178, 397, 70, 217, 208, 118, 399, 341, 251, 41, 140, 275, 319, 46, 233, 147, 193, 7, 49, 108, 370, 126, 111, 338, 243, 398, 265, 209, 127, 232, 273, 364, 48, 259, 186, 271, 221, 197, 138, 290, 150, 81, 231, 311, 342, 42, 215, 14, 212, 252, 169, 310, 143, …
```
> Eager load photos to reduce the number of queries executed

- app/models/garden.rb
- app/models/notification.rb
- app/models/post.rb
- app/views/gardens/_form.html.haml
- app/views/notifications/_form.html.haml
- app/views/posts/_form.html.haml
> Add title validations

- app/models/harvest.rb
- app/views/harvests/_form.html.haml
- spec/controllers/harvests_controller_spec.rb
- spec/features/harvests/harvesting_a_crop_spec.rb
> Fix plant parts / harvests

- app/controllers/notifications_controller.rb
- spec/controllers/notifications_controller_spec.rb
Version of #813 w/test
Implements #507
> Mark notifications read when replying

- app/controllers/notifications_controller.rb
Fixes: https://github.com/Growstuff/growstuff/issues/507
> If i reply to a notification directly, it's not marked as read. #507

- .gitignore
- config/database.yml.example
So people can change it if needed (which is needed on Nitrous)
> Moving database.yml and adding gitignore

- script/deploy-tasks.sh
Since we switched from less to sass, we now need to precompile assets to get new css/js like the Bootstrap accessibility plugin (#803) to work.
> Precompile css and js with sass

- app/views/gardens/_thumbnail.html.haml
- app/views/members/_location.html.haml
- app/views/members/_map.html.haml
- app/views/places/show.html.haml
- app/views/plantings/show.html.haml
- app/views/seeds/show.html.haml
- spec/features/member_profile_spec.rb
- spec/features/places/searching_a_place_spec.rb
Mostly fixes #872 - adjusts the place page to be more generic, and adds more links from seeds or plantings.
> Improve nearby places links

- app/assets/stylesheets/overrides.sass
>  Clip long text in definition lists within panels

- app/views/seeds/_thumbnail.html.haml
> make seed card heading link to seed page and add owner link. Fixes #873

- Gemfile.lock
- app/controllers/photos_controller.rb
Back when I made the horrible nested if of doom on the photos controller, we talked about eventually refactoring it for readability. Here we go. It could probably be abstracted further (item assignment and actual photo attachment lines), but this is much better already.
> refactor photo controller create for readability

- app/views/photos/show.html.haml
- config/locales/en.yml
- spec/features/photos/show_photo_spec.rb
> Use standardized & translateable strings for the photo show page

- app/assets/stylesheets/overrides.sass
- app/views/layouts/_crowdfunding.html.haml
- app/views/layouts/application.html.haml
As per convo on #930 commits - do we need it at the moment? No. Will we need it again... maybe? But we can no doubt revert this change with minimal effort
> Remove crowdfunding code

- CONTRIBUTORS.md
- app/controllers/sessions_controller.rb
- config/routes.rb
- spec/features/signin_spec.rb
Issue 910.
This is my first non-trivial (ie, grammar) open source contribution. Did I do it right? What can I improve?
> #910: Crop approval flash alert for wranglers upon sign in

- spec/helpers/seeds_helper_spec.rb
Adding some test coverage while I am learning about the application, if that is ok
> Add test coverage for Seeds Helper

- Gemfile
- Gemfile.lock
- config/initializers/devise.rb
Devise 4.1 etc is out, but there's a few deprecations on the way there.
This should get us part way there and let us clean things up.
https://github.com/plataformatec/devise/blob/master/CHANGELOG.md describes the changes since 3.5.10 to 4.0.3
> Upgrade to devise 4.0.*

- Capfile
Finishes work started in 93e468876dd4fbdad8b226d322bb16e310980652.
> Remove the Capistrano configuration file

- app/views/comments/_single.html.haml
- app/views/posts/_single.html.haml
- spec/features/comments/commenting_a_comment_spec.rb
- spec/features/posts/posting_a_post_spec.rb
- spec/views/posts/_single.html.haml_spec.rb
Taking the remaining bits from #704 and finishing off #476.
> Issue 476 edited by date on comments and posts

- app/views/posts/_summary.html.haml
Fixes #875. ~~I haven't yet tested this properly, but putting it out there so Travis checks it.~~
Now ready.
> Fix #875 edited date on comments on homepage

- app/views/comments/show.html.haml
- app/views/crops/show.html.haml
- app/views/gardens/show.html.haml
- app/views/harvests/show.html.haml
- app/views/members/show.html.haml
- app/views/plantings/show.html.haml
- app/views/posts/show.html.haml
- app/views/scientific_names/show.html.haml
- app/views/seeds/show.html.haml
Oops; don't need to render quite so much on pages like http://staging.growstuff.org/crops/blackcurrant !
> Various bugfixes for facebook/opengraph

- Gemfile
- Gemfile.lock
A variety of minor upgrades, including devise and geocoder.
> Update various gems

- spec/helpers/gardens_helper_spec.rb
> Add test coverage for GardensHelper

- app/helpers/crops_helper.rb
- spec/helpers/crops_helper_spec.rb
For #920 
Will go write explicit coverage of the helper in a bit, if this is the actual issue.
> Deal with .nil quantity of a seed in rendering helper

- CONTRIBUTORS.md
- app/helpers/application_helper.rb
- app/helpers/crops_helper.rb
- app/views/forums/index.html.haml
- app/views/gardens/_thumbnail.html.haml
- app/views/gardens/show.html.haml
- app/views/members/_gardens.html.haml
- app/views/members/_stats.html.haml
- app/views/members/_thumbnail.html.haml
- app/views/posts/_comments.html.haml
- app/views/posts/_single.html.haml
- config/locales/en.yml
- spec/helpers/application_helper_spec.rb
[#919](https://github.com/Growstuff/growstuff/issues/919)
> Replace pluralize calls

- Gemfile.lock
Minor version bump from the rails 4.2 upgrade work
> Upgrade gibbon

- config/environments/production.rb
- config/environments/staging.rb
I've already pressed the buttons in Heroku to make it go. There is an open question of whether the API key Heroku generated will work. If not, I have the one SP generated, and we can swap that out in Heroku's config without needing another code push. That's something to check on staging.
> update to SparkPost's mailserver

- config/routes.rb
Reverts Growstuff/growstuff#999
> Revert "lets encrypt challenge page"

- app/controllers/pages_controller.rb
Reverts Growstuff/growstuff#1002
> Revert "challenge code"

- .travis.yml
- script/check_contributors_md
Results of testing this locally (the exit value of the last command is in my prompt):
```
0 $ TRAVIS=true TRAVIS_REPO_SLUG=growstuff/growstuff TRAVIS_PULL_REQUEST=1007 script/check_contributors_md
Checking to see if you're in CONTRIBUTORS.md...
Thanks for your contribution, ctlewitt!
Please add your name and GitHub handle to the file CONTRIBUTORS.md,
commit it, and update your PR.
1 $ TRAVIS=true TRAVIS_REPO_SLUG=growstuff/growstuff TRAVIS_PULL_REQUEST=1008 script/check_contributors_md
Checking to see if you're in CONTRIBUTORS.md...
- Miles Gould / [pozorvlak](https://github.com/pozorvlak)
0 $ script/check_contributors_md
Checking to see if you're in CONTRIBUTORS.md...
- Miles Gould / [pozorvlak](https://github.com/pozorvlak)
0 $
```
> Check PR author is in CONTRIBUTORS.md under Travis

- app/controllers/alternate_names_controller.rb
- app/controllers/comments_controller.rb
- app/controllers/harvests_controller.rb
- app/controllers/photos_controller.rb
We can just fall back to the default implementation for these.
See comments on #972 for background.
> Remove "show" methods that just do the default

- app/models/crop.rb
- app/models/harvest.rb
- app/views/harvests/_thumbnail.html.haml
- spec/models/crop_spec.rb
- spec/models/harvest_spec.rb
Fixes #997 and #1017 (though performance might need a bit of consideration I think)
> If a harvest doesn't have any photos, try to look at the crop's default photo

- app/helpers/application_helper.rb
- app/views/crops/show.html.haml
- spec/features/crops/crop_detail_page_spec.rb
#967 now with 100% less conflicts, fixes #864
> Gardenate attempt 2

- app/assets/javascripts/crops.js.erb
- app/assets/javascripts/members.js.erb
- app/assets/javascripts/places.js.erb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/staging.rb
Fixes #981 Adds an access token, but from my free account (limited to 50k views, in use elsewhere).
> #981 Add mapbox v4

- app/assets/javascripts/append_date.js.coffee
>  Ensure we look at the current control, not the entire collection when marking planting finished

- config/environments/production.rb
> Fix map token in prod configuration

- app/views/crops/show.html.haml
- spec/features/crops/crop_detail_page_spec.rb
> Add links to OpenFarm

- app/models/crop.rb
> Prevent FactoryGirl from trying to connect to ElasticSearch in tests

- script/check_contributors_md
My PRs are being failed by travis, because it thinks my username is 'Br3nda', and the contributors file says 'br3nda'
This makes the grep for contributors ignore case.
> Contributors check case-insentive

- config/locales/en.yml
same key appears again (with different value) 5 lines below
> Removed duplicate wiki_linktext

- .travis.yml
- Gemfile
This is pretty much the same as #979. I forked, and merged in dev branch, and got Green build reliably on travis.
Hoping for the same here.
> Use phantomjs 211 in travis

- lib/tasks/growstuff.rake
codeship was failing un-related PRs because of this duplication.
> Reduced code duplication in growstuff.rake

- config/locales/en.yml
This is the result of  `i18n-tasks normalise`.
It sorts the file. This is considered good practise for readability.
I have a second PR to submit that removed unused translations - but it is hard to read unless we normalise the file first.
> Normalise translation file

- .travis.yml
I *think* this is all that's necessary, though it's a bit hard to test :-)
> Auto-deploy to production on successful merge

- Gemfile
- Gemfile.lock
I have no evidence this will fix the poltergeist CI errors, but it works for me.
> Upgrading poltergeist

- .travis.yml
- .yamllint
I ran yamllint over the file, and fixed up some bits.
This includes changes the phantomjs downloading script that's inside this yaml file. I've wrapped the lines, which i think makes it easier to read.
I changed the direct posgresql create command to instead go via rake and therefore the settings in rails db config.
I also changed the phantomjs download url to the official distribution of phantomjs. Maybe it changed since this was set up?
I've included the yamllint config I used. I haven't added yamllint checking into travis yet, as there's some other files that need a clean up first.
> Travis file lint and clean

- app/models/crop.rb
hey @CloCkWeRX I made it more readable. It'll still claim to have potential for SQL injection, which I still think it's wrong about (because private method operating on local CSV file), so maybe can tell Code Climate to ignore...
> Improve crop model

- app/helpers/plantings_helper.rb
fix for #1079
Check we have a planted_at ts before doing maths with it
> Check we have a planted_at ts before using

- app/models/concerns/photo_capable.rb
starts #1107 
need to add require changes in photo.rb and photos_controller.rb but can't really test until #1106 is fixed
> WIP: add require_relative to photo_capable concern for constants

- app/controllers/account_types_controller.rb
- app/controllers/accounts_controller.rb
- app/controllers/alternate_names_controller.rb
- app/controllers/comments_controller.rb
- app/controllers/crops_controller.rb
- app/controllers/gardens_controller.rb
- app/controllers/harvests_controller.rb
- app/controllers/notifications_controller.rb
- app/controllers/orders_controller.rb
- app/controllers/photos_controller.rb
- app/controllers/plant_parts_controller.rb
- app/controllers/plantings_controller.rb
- app/controllers/posts_controller.rb
- app/controllers/products_controller.rb
- app/controllers/roles_controller.rb
- app/controllers/scientific_names_controller.rb
- app/controllers/seeds_controller.rb
removed lots of unnecesary loading of a controller's resource. The `load_and_authorize_resource` already does this for us.
> Cancan already loads the resource

- app/controllers/harvests_controller.rb
- app/models/ability.rb
- app/models/harvest.rb
- app/models/planting.rb
- app/views/harvests/_form.html.haml
- app/views/harvests/show.html.haml
- app/views/plantings/_planting_harvest.html.haml
- app/views/plantings/_thumbnail.html.haml
- app/views/plantings/show.html.haml
- config/routes.rb
- db/migrate/20170104035248_add_planting_ref_to_harvests.rb
- db/schema.rb
- spec/controllers/harvests_controller_spec.rb
This links a harvest to a planting (and thus through to a garden)
Initially only displaying on plantings - but we can link it through to see what the yield from a garden is, season by season, year to year. 
We could also link harvest it to companion plantings, and optional crop rotation - and other events we implement later.
This is for #1137
> Link a harvest to a planting, and display

- Gemfile
Same gems, but each cluster is sorted
> Bundle alphabetical order to comply with stricter rubocop

- config/locales/en.yml
> Removed unwanted quotes in member name in menu

- app/assets/stylesheets/overrides.sass
> Fix display of gardens on smaller screens

- app/controllers/crops_controller.rb
- app/models/notification.rb
- lib/tasks/growstuff.rake
currently these are broken:
* follow
* send message
*  suggest crop
* planting reminders
* wrangler notifications
* crop approvals
This PR is in dev, I really like it pushed live to fix these.
> Fix crashing on email send - HOTFIX to master

- app/controllers/crops_controller.rb
- app/models/ability.rb
- app/views/crops/index.html.haml
- app/views/crops/requested.haml
- config/locales/en.yml
- config/routes.rb
- spec/features/crops/requested_crops_spec.rb
This is for  #1039
Needs specs
> Member can see crops they have requested

- app/models/harvest.rb
i think this will get us closer to being able to I18n.t this.
> Simplified harvest.to_s

- app/controllers/plantings_controller.rb
the code was writing to @plantings over and over, and then returning it to be written into @plantings again.
this is better
> Reduce complexity of plantings controller

- app/views/notifications/_form.html.haml
- app/views/notifications/index.html.haml
- app/views/notifications/new.html.haml
- app/views/notifications/reply.html.haml
- app/views/notifications/show.html.haml
my git stash is getting unwieldly, so sending this folder that is cleaned up before going back to trickier haml in gardens
> Haml clean up for notifications

- app/views/members/_avatar.html.haml
- app/views/members/_contact.html.haml
- app/views/members/_gardens.html.haml
- app/views/members/_location.html.haml
- app/views/members/_map.html.haml
- app/views/members/_stats.html.haml
- app/views/members/_thumbnail.html.haml
- app/views/members/finish_signup.haml
- app/views/members/index.html.haml
- app/views/members/nearby.html.haml
- app/views/members/show.html.haml
- app/views/members/show.rss.haml
- app/views/members/view_followers.html.haml
- app/views/members/view_follows.html.haml
my git stash is getting unwieldly, so sending this folder that is cleaned up before going back to trickier haml in gardens
> Haml clean up for members

- app/views/harvests/show.html.haml
- app/views/plantings/show.html.haml
- app/views/products/show.html.haml
- app/views/seeds/show.html.haml
Most of the growstuff_markdown has strip tag -- but 4 of them don't
These are being actively exploited by a spammer.
> stripping html from markdown

- .rubocop_todo.yml
- app/controllers/alternate_names_controller.rb
- app/views/admin/index.html.haml
Move respond to.
Removed some json responders that aren't being used
> Simplified alternate names controller.

- app/controllers/gardens_controller.rb
because when you create/update a garden , you don't get to choose who the owner is
> don't allow owner in params

- Gemfile
- Gemfile.lock
> Upgrade to current Hashie

- app/controllers/comments_controller.rb
- spec/controllers/comments_controller_spec.rb
I also added more tests for when trying to delete or edit a comment you didn't write.
> DRY comments controller

- .rubocop.yml
- app/models/alternate_name.rb
- app/models/crop.rb
- app/models/csv_importer.rb
- app/models/scientific_name.rb
- db/seeds.rb
- lib/tasks/growstuff.rake
- spec/models/crop_spec.rb
- spec/models/scientific_name_spec.rb
I've pulled the csv import out to CsvImporter class
It's only called from db:seeds and a rake task.
> Shrinking the giant crop model code

- app/models/csv_importer.rb
- spec/models/crop_spec.rb
Now matches the old functionality.
> Fix up csv importer, should make duplicates

- db/schema.rb
Travis is showing the schema.rb gets modified every migration.
Checkin in the modifications.
> Schema is out of sync -- fixing

- script/install_linters
This tells bundle-audit to download the latest security advisories
> Bundle audit needs updating in test runs

- spec/models/crop_spec.rb
- spec/models/garden_spec.rb
- spec/models/post_spec.rb
i don't think these assertions were running ..
> bugfix in some spec expectations

- Gemfile.lock
- public/404.html
- public/422.html
- public/500.html
Fix #992
Fix #492
Rebase of #1258
> Update public error pages

- app/models/crop.rb
Uses the existing scope to find approved crops.
> Reduced duplication of the term "approved" in crop model

- .gitignore
- .overcommit.yml
- package.json
- script/install_linters
> Install npm modules locally

- CONTRIBUTORS.md
- app/models/post.rb
> Use presence instead of regex validation

- app/controllers/plantings_controller.rb
- app/models/ability.rb
- spec/controllers/plantings_controller_spec.rb
This only affects the display on the form. But the specs were displaying a garden from another member on the #new -- which is incorrect and really confused me while working on another feature.
Also restricted plantings to crops that are approved
> Limited plantings to member's own garden, and approved crops

- CONTRIBUTORS.md
adding a missing contributor @meganft from #1280
> Added Megan to contributors

- app/controllers/harvests_controller.rb
- app/helpers/application_helper.rb
- app/views/harvests/_nav.haml
- app/views/harvests/index.html.haml
- app/views/plantings/_planting_harvest.html.haml
- app/views/plantings/index.html.haml
- app/views/seeds/index.html.haml
- config/locales/en.yml
The routes already existed for this, but wasn't filled in.
Noticed when starting work on #474
> View harvests for a planting

- CONTRIBUTORS.md
- config/initializers/inflections.rb
- spec/features/crops/inflections_spec.rb
Added to the list of irregular crop pluralizations and added tests for the ones that were added as well as ones that were on the list already but not accounted for in tests.
> Update irregular crop pluralizations issue #619

- Gemfile.lock
> Gemfile.lock bumping ruby version to match other files

- app/models/garden.rb
- app/views/gardens/show.html.haml
- app/views/members/_gardens.html.haml
> Reduce page query count

- Gemfile
- Gemfile.lock
- app/controllers/photos_controller.rb
- app/models/planting.rb
- app/services/planting_predictions.rb
- spec/models/planting_spec.rb
Moving the planting prediction calculations out to their own file. 
I hope to expand this to perennial/annual and make predictions of harvest times.
> Planting predictions

- CONTRIBUTORS.md
- README.md
closes issue [#1134](https://github.com/Growstuff/growstuff/issues/1134)
> added security contact info to readme

- script/heroku_maintenance.rb
Attempting to fix the heroku deploys - this is tricky to test so i haven't.
> Migrate to new heroku platform api - maintenance mode trigger

- script/heroku_maintenance.rb
maintenance is just an attribute now
> Update heroku maintenance script - maintenance is just an attribute now

- app/views/notifications/index.html.haml
> Display messages even when member is deleted

- app/views/harvests/_thumbnail.html.haml
to be consistent with the rest of the site
> Link harvest thumbnails to harvests

- app/models/crop.rb
> Randomise the crops on the homepage

- app/controllers/photos_controller.rb
fixes #1463
This needs some specs too
> Add id and type back to photos#new

- app/controllers/authentications_controller.rb
- app/views/devise/registrations/_edit_apps.html.haml
also fixes #1479 
(someone please test FB, i don't have an account)
> Fix Growstuff::OauthSignupAction not found error when connecting flickr

- script/check_contributors_md.rb
Auto corrected by following EmptyLine
Click [here](https://awesomecode.io/projects/55/ruby_config_groups/527) to configure it on awesomecode.io
> Auto corrected by following EmptyLine

- spec/controllers/account_types_controller_spec.rb
- spec/controllers/comments_controller_spec.rb
- spec/controllers/gardens_controller_spec.rb
- spec/controllers/harvests_controller_spec.rb
- spec/controllers/likes_controller_spec.rb
- spec/controllers/photo_associations_controller_spec.rb
- spec/controllers/photos_controller_spec.rb
- spec/controllers/plantings_controller_spec.rb
- spec/controllers/shop_controller_spec.rb
- spec/features/crops/crop_detail_page_spec.rb
- spec/features/crops/requested_crops_spec.rb
- spec/features/gardens_spec.rb
- spec/features/members/deletion_spec.rb
- spec/features/plantings/planting_a_crop_spec.rb
- spec/features/seeds/seed_photos.rb
- spec/features/signout_spec.rb
- spec/models/crop_spec.rb
- spec/models/member_spec.rb
- spec/models/photo_spec.rb
- spec/models/planting_spec.rb
- spec/models/post_spec.rb
- spec/models/role_spec.rb
- spec/models/seed_spec.rb
- spec/views/crops/_planting_advice.html.haml_spec.rb
- spec/views/home/_crops.html.haml_spec.rb
- spec/views/members/index.html.haml_spec.rb
- spec/views/plantings/index.html.haml_spec.rb
- spec/views/plantings/show.html.haml_spec.rb
- spec/views/posts/show.html.haml_spec.rb
Auto corrected by following RSpec/EmptyLineAfterFinalLet
Click [here](https://awesomecode.io/projects/55/ruby_configs/14387) to configure it on awesomecode.io
> Auto corrected by following RSpec/EmptyLineAfterFinalLet

- app/models/csv_importer.rb
- db/seeds.rb
- spec/controllers/photo_associations_controller_spec.rb
Auto corrected by following Style/RescueStandardError
Click [here](https://awesomecode.io/projects/55/ruby_configs/14340) to configure it on awesomecode.io
> Auto corrected by following Style/RescueStandardError

- spec/features/crops/alternate_name_spec.rb
- spec/features/crops/crop_detail_page_spec.rb
- spec/features/following_spec.rb
- spec/features/member_profile_spec.rb
- spec/features/places/searching_a_place_spec.rb
- spec/features/plantings/planting_a_crop_spec.rb
- spec/features/scientific_name_spec.rb
- spec/features/shared_examples/crop_suggest.rb
- spec/models/crop_spec.rb
- spec/models/like_spec.rb
- spec/models/post_spec.rb
Auto corrected by following RSpec/NotToNot
Click [here](https://awesomecode.io/projects/55/ruby_configs/14396) to configure it on awesomecode.io
> Auto corrected by following RSpec/NotToNot

- app/models/planting.rb
Auto corrected by following Style/MutableConstant
Click [here](https://awesomecode.io/projects/55/ruby_configs/14247) to configure it on awesomecode.io
> Auto corrected by following Style/MutableConstant

- spec/features/crops/crop_detail_page_spec.rb
Auto corrected by following RSpec/MultipleSubjects
Click [here](https://awesomecode.io/projects/55/ruby_configs/14395) to configure it on awesomecode.io
> Auto corrected by following RSpec/MultipleSubjects

- app/controllers/crops_controller.rb
> Re-instated the extra fields on crop.json

- app/views/plantings/_form.html.haml
- spec/views/plantings/_form.html.haml_spec.rb
> Fix missing ordering. Plantings form's list of gardens

- spec/controllers/member_controller_spec.rb
- spec/models/photo_spec.rb
Auto corrected by following Style/Lambda
Click [here](https://awesomecode.io/projects/55/ruby_configs/14164) to configure it on awesomecode.io
> Auto corrected by following Style/Lambda

- spec/features/crops/crop_detail_page_spec.rb
- spec/features/crops/crop_photos_spec.rb
- spec/features/seeds/seed_photos.rb
- spec/models/crop_spec.rb
- spec/models/role_spec.rb
- spec/requests/api/v1/crop_request_spec.rb
- spec/requests/api/v1/gardens_request_spec.rb
- spec/requests/api/v1/harvest_request_spec.rb
- spec/requests/api/v1/member_request_spec.rb
- spec/requests/api/v1/photos_request_spec.rb
- spec/requests/api/v1/plantings_request_spec.rb
- spec/requests/api/v1/seeds_request_spec.rb
- spec/views/crops/_planting_advice.html.haml_spec.rb
- spec/views/harvests/show.html.haml_spec.rb
- spec/views/posts/show.html.haml_spec.rb
Auto corrected by following RSpec/LeadingSubject
Click [here](https://awesomecode.io/projects/55/ruby_configs/14394) to configure it on awesomecode.io
> Auto corrected by following RSpec/LeadingSubject

- CONTRIBUTORS.md
- app/controllers/photos_controller.rb
- app/controllers/plantings_controller.rb
- app/models/photo.rb
- db/migrate/20180118112809_add_datetaken_to_photos.rb
- db/schema.rb
This branch contains the work by @mftaff on #1554, with the newly rebased dev branch.
This PR should be much cleaner to merge
> Add date_taken to photos

- app/assets/stylesheets/overrides.sass
- app/views/home/_crops.html.haml
- app/views/home/_plantings.html.haml
- app/views/home/_seeds.html.haml
- app/views/home/index.html.haml
- app/views/plantings/_list.html.haml
> Layout fixes for mobile and smaller screens 

- app/views/harvests/_planting.haml
https://github.com/Growstuff/growstuff/issues/1595
Only show "Planting: Is this from one of these plantings?" if there is a matching planting.
> Only show planting suggestion if there's a match

- Rakefile
- config/application.rb
- config/boot.rb
- config/environment.rb
- script/rails
- spec/rails_helper.rb
This reverts commit a5b84403bb9f94f322a7fb89f80d93e1068fbff6.
> Revert "Auto corrected by following Style/ExpandPathArguments"

- app/mailers/notifier.rb
> Order plantings and harvests in email

- spec/factories/member.rb
Rubocop is failing the build on travis. Here's the style change it seems to need.
> Style fix up

- spec/factories/alternate_names.rb
- spec/factories/authentications.rb
- spec/factories/crop.rb
- spec/factories/forums.rb
- spec/factories/garden.rb
- spec/factories/harvests.rb
- spec/factories/member.rb
- spec/factories/notifications.rb
- spec/factories/photos.rb
- spec/factories/planting.rb
- spec/factories/post.rb
- spec/factories/roles.rb
- spec/factories/scientific_name.rb
- spec/factories/seeds.rb
Statically defined attributes in FactoryBot are being deprecated soon.
https://github.com/thoughtbot/factory_bot/pull/1135
> Auto corrected by following Ruby FactoryBot/AttributeDefinedStatically

- config/environments/production.rb
- config/environments/staging.rb
> Force to redirect to ssl

- app/assets/stylesheets/bootstrap-accessibility.css
Auto corrected by following Format Css Code
Click [here](https://awesomecode.io/repos/Growstuff/growstuff/css_format_config) to configure it on awesomecode.io
> Auto corrected by following Format Css Code

- Gemfile
- Gemfile.lock
- app.json
- config/application.yml.example
- config/environments/production.rb
> Switch to SendGrid (remove sparkhost)

- spec/controllers/api/v1/plantings_controller_spec.rb
Auto corrected by following Lint Ruby rspec layout
Click [here](https://awesomecode.io/repos/Growstuff/growstuff/ruby_config_groups/732) to configure it on awesomecode.io
> Auto corrected by following Lint Ruby rspec layout

- spec/views/crops/_planting_advice.html.haml_spec.rb
Auto corrected by following Lint Ruby RSpec/SharedContext
Click [here](https://awesomecode.io/repos/Growstuff/growstuff/ruby_lint_configs/26025) to configure it on awesomecode.io
> Auto corrected by following Lint Ruby RSpec/SharedContext

- spec/helpers/buttons_helper_spec.rb
Auto corrected by following Lint Ruby RSpec/ReturnFromStub
Click [here](https://awesomecode.io/repos/Growstuff/growstuff/ruby_lint_configs/26010) to configure it on awesomecode.io
> Auto corrected by following Lint Ruby RSpec/ReturnFromStub

- spec/helpers/crops_helper_spec.rb
Auto corrected by following Lint Ruby Space
Click [here](https://awesomecode.io/repos/Growstuff/growstuff/ruby_config_groups/879) to configure it on awesomecode.io
> Auto corrected by following Lint Ruby Space

- spec/features/gardens/gardens_index_spec.rb
- spec/features/places/searching_a_place_spec.rb
- spec/features/plantings/planting_a_crop_spec.rb
- spec/helpers/application_helper_spec.rb
- spec/helpers/crops_helper_spec.rb
- spec/lib/actions/oauth_signup_action_spec.rb
- spec/models/alternate_name_spec.rb
- spec/models/crop_spec.rb
- spec/models/follow_spec.rb
- spec/models/garden_spec.rb
- spec/models/harvest_spec.rb
- spec/models/member_spec.rb
- spec/models/planting_spec.rb
- spec/models/post_spec.rb
- spec/models/scientific_name_spec.rb
- spec/models/seed_spec.rb
- spec/support/is_likeable.rb
- spec/views/devise/confirmations/new_spec.rb
- spec/views/devise/mailer/confirmation_instructions_spec.rb
- spec/views/devise/mailer/reset_password_instructions_spec.rb
- spec/views/devise/mailer/unlock_instructions_spec.rb
- spec/views/devise/registrations/edit_spec.rb
- spec/views/devise/registrations/new_spec.rb
- spec/views/devise/sessions/new_spec.rb
- spec/views/devise/shared/_links_spec.rb
- spec/views/devise/unlocks/new_spec.rb
- spec/views/layouts/_header_spec.rb
- spec/views/layouts/_meta_spec.rb
- spec/views/notifier/notify.html.haml_spec.rb
- spec/views/scientific_names/show.html.haml_spec.rb
Auto corrected by following Lint Ruby RSpec/ExampleWording
Click [here](https://awesomecode.io/repos/Growstuff/growstuff/ruby_lint_configs/25575) to configure it on awesomecode.io
> Auto corrected by following Lint Ruby RSpec/ExampleWording

- spec/controllers/comments_controller_spec.rb
- spec/features/signout_spec.rb
- spec/models/crop_spec.rb
Auto corrected by following Lint Ruby EmptyLine
Click [here](https://awesomecode.io/repos/Growstuff/growstuff/ruby_config_groups/881) to configure it on awesomecode.io
> Auto corrected by following Lint Ruby EmptyLine

- app/controllers/crops_controller.rb
- spec/controllers/crops_controller_spec.rb
- spec/features/crops/delete_crop_spec.rb
- spec/features/crops/show_spec.rb
Crop deletion doesn't work (returns 500 error on production)
this fixes and adds tests.
> Fixing crop deleting and adding tests

- spec/models/garden_type.rb
Auto corrected by following Lint Ruby RSpecEmptyLine
Click [here](https://awesomecode.io/repos/Growstuff/growstuff/ruby_config_groups/882) to configure it on awesomecode.io
> Auto corrected by following Lint Ruby RSpecEmptyLine

- spec/controllers/garden_types_controller_spec.rb
- spec/models/garden_spec.rb
Auto corrected by following Lint Ruby RSpec/AlignLeftLetBrace
Click [here](https://awesomecode.io/repos/Growstuff/growstuff/ruby_lint_configs/25335) to configure it on awesomecode.io
> Auto corrected by following Lint Ruby RSpec/AlignLeftLetBrace

- spec/models/garden_type.rb
Auto corrected by following Lint Ruby RSpec/ExpectChange
Click [here](https://awesomecode.io/repos/Growstuff/growstuff/ruby_lint_configs/25605) to configure it on awesomecode.io
> Auto corrected by following Lint Ruby RSpec/ExpectChange

- spec/controllers/garden_types_controller_spec.rb
- spec/views/garden_types/edit.html.haml_spec.rb
- spec/views/garden_types/new.html.haml_spec.rb
Auto corrected by following Lint Ruby RSpec/HookArgument
Click [here](https://awesomecode.io/repos/Growstuff/growstuff/ruby_lint_configs/25680) to configure it on awesomecode.io
> Auto corrected by following Lint Ruby RSpec/HookArgument

- spec/controllers/garden_types_controller_spec.rb
- spec/models/garden_spec.rb
Auto corrected by following Lint Ruby RSpec/AlignRightLetBrace
Click [here](https://awesomecode.io/repos/Growstuff/growstuff/ruby_lint_configs/25350) to configure it on awesomecode.io
> Auto corrected by following Lint Ruby RSpec/AlignRightLetBrace

- config/environments/production.rb
> Fixes wrong host name in emails

- spec/features/crops/crop_detail_page_spec.rb
- spec/features/gardens/actions_spec.rb
- spec/features/harvests/browse_harvests_spec.rb
- spec/features/home/home_spec.rb
- spec/features/seeds/seed_photos.rb
- spec/helpers/photos_helper_spec.rb
- spec/views/crops/_planting_advice.html.haml_spec.rb
- spec/views/members/show.rss.haml_spec.rb
- spec/views/posts/show.html.haml_spec.rb
Auto corrected by following Lint Ruby RSpec/ImplicitSubject
Click [here](https://awesomecode.io/repos/Growstuff/growstuff/ruby_lint_configs/29255) to configure it on awesomecode.io
> Auto corrected by following Lint Ruby RSpec/ImplicitSubject

- Gemfile
- Gemfile.lock
- app/views/members/_avatar.html.haml
- package.json
- script/percy.sh
- spec/factories/member.rb
- spec/features/percy/percy_spec.rb
- spec/spec_helper.rb
- yarn.lock
Adding a "visual differences" tool, to make it easier to review changes to look/layout
> Add percy - visual difference detection

- spec/features/percy/percy_spec.rb
This pull request applies style fixes from code review by [CodeFactor](https://www.codefactor.io).
---
For more information, click [here](https://www.codefactor.io/repository/github/growstuff/growstuff/issues?category=Style).
> Apply fixes from CodeFactor

- config/locales/en.yml
> Remove stray \n in translation

- Gemfile.lock
- app/views/home/index.html.haml
- app/views/members/show.html.haml
- config/locales/en.yml
- spec/features/locale_spec.rb
- spec/features/members/profile_spec.rb
closes #2007 
fixes members#show error when planted_at is nil
and add lots of specs
> Fixes profile page errors on staging

- app/views/devise/passwords/edit.html.haml
- app/views/devise/passwords/new.html.haml
- app/views/devise/registrations/_delete.html.haml
- app/views/devise/registrations/_edit_apps.html.haml
- app/views/devise/registrations/_edit_email.html.haml
- app/views/devise/registrations/_edit_password.html.haml
- app/views/devise/registrations/_edit_profile.html.haml
- app/views/devise/registrations/new.html.haml
- app/views/devise/unlocks/new.html.haml
I've just copied what @Br3nda did in #2018. `git grep` shows no further uses of `devise_error_messages!`.
> Fix remaining uses of devise_error_messages!

- app/helpers/application_helper.rb
- app/views/members/_member.haml
> Fixing pluralising member's items on member card

- app/views/home/_discuss.html.haml
- app/views/home/_members.html.haml
- app/views/home/_seeds.html.haml
- app/views/home/index.html.haml
- app/views/members/_location.html.haml
- app/views/members/_member.haml
- app/views/seeds/_card.html.haml
Fix up layout on home page, including truncating long locations like taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiwhenuakitanatahu
fixes #2020
> Homepage layout

- app/views/plantings/_form.html.haml
Fixes a regression
fixes #2037
> only show active gardens on planting form

- app/views/layouts/_header.html.haml
> fix display of inbox item in menu

- CONTRIBUTING.md
> Removed mention of jasmine

- app/assets/stylesheets/_plantings.scss
- app/assets/stylesheets/overrides.scss
we were overriding the colours
> fix display of badges (colours)

- config/environments/production.rb
- lib/haml/filters/growstuff_markdown.rb
- spec/features/members/deletion_spec.rb
- spec/lib/haml/filters/growstuff_markdown_spec.rb
fixes #2072. by not using full urls in growstuff markdown links to crops
Also moves to reading host from env, so we can have different ones on staging and prod
> Fixes markdown on staging that links to production

- app/controllers/photo_associations_controller.rb
- app/controllers/photos_controller.rb
- app/models/concerns/photo_capable.rb
- app/models/crop.rb
- app/models/photo.rb
- app/models/photo_association.rb
- app/views/photos/_association_delete_button.haml
- config/routes.rb
- db/migrate/20190130090437_add_crop_to_photographings.rb
- db/migrate/20190712234859_rename_photographings.rb
- db/schema.rb
now it matches the name of its controller, and it is clearer to understand. This feels more railsy
> Renamed photographings to photo associations

- app/controllers/admin/members_controller.rb
- app/controllers/members_controller.rb
- app/views/admin/members/index.html.haml
- app/views/members/_follow_buttons.haml
- app/views/members/show.html.haml
- app/views/members/show.rss.haml
- config/routes.rb
- lib/tasks/growstuff.rake
- spec/controllers/member_controller_spec.rb
- spec/features/members/ban_spec.rb
- spec/models/photo_spec.rb
and easier way to ban the users that are posting spam
closes  #2091
> Ban hammer

- .travis.yml
- script/install_elasticsearch.sh
This fixes the postgresql not running errors on travis
We'll need to upgrade postgresql soon, to get to new ubuntu stable next year.
> fixing travis build

- Gemfile
- Gemfile.lock
their ssl cert has expired yet again. The gem we want appears to be on rubygems.org now
> Stop using rails-assets.org

- CONTRIBUTORS.md
- app/views/gardens/show.html.haml
Addressing remaining feedback on #2104. It looked like some clean up may have already been done. I wasnt sure if we want to move the create planting out of the actions dropdown or not. There is quite a bit of conditional logic surrounding that action that might be nice to keep in a single place. Would we want to move all buttons out of the actions dropdown?
> small ui tweak to the show garden view

- Gemfile
- Gemfile.lock
> Add source for leaflet

- app/controllers/gardens_controller.rb
- app/views/gardens/_previously.haml
- app/views/gardens/show.html.haml
> Group previous plantings by year

- Procfile
- config/puma.rb
> Switch from unicorn to puma

- CONTRIBUTORS.md
- app/helpers/application_helper.rb
- app/views/devise/registrations/_edit_profile.html.haml
- spec/factories/member.rb
- spec/features/percy/percy_spec.rb
- spec/helpers/application_helper_spec.rb
> Switch to HTTPS for Gravatar urls

- app/assets/stylesheets/overrides.scss
- app/views/gardens/index.html.haml
> Link to jump to garden

- db/migrate/20191119020643_upgrade_cms.rb
- db/schema.rb
> Finish the CMS upgrade and fix #2098

- db/migrate/20191119030244_cms_tags.rb
copied from https://github.com/comfy/comfortable-mexican-sofa/wiki/HowTo:-Upgrade-CMS-From-1.12-to-2.0
> Migrate CMS tags

- Gemfile
- Gemfile.lock
- app/controllers/crops_controller.rb
- app/helpers/crops_helper.rb
- app/helpers/photos_helper.rb
- app/models/concerns/photo_capable.rb
- app/models/crop.rb
- app/models/scientific_name.rb
- app/views/crops/_harvests.html.haml
- app/views/crops/_photos.html.haml
- app/views/crops/_plantings.html.haml
- app/views/crops/_thumbnail.html.haml
- app/views/crops/_varieties.html.haml
- app/views/home/_plantings.html.haml
- app/views/layouts/_footer.html.haml
- app/views/layouts/application.html.haml
- config/environments/development.rb
- spec/models/crop_spec.rb
reduced home page queries from 91 to 12
> Reduce number of db queries

- app/models/concerns/photo_capable.rb
- app/models/concerns/predict_planting.rb
After testing on staging, release the photo query caching.
> Release caching

- Gemfile
- Gemfile.lock
- spec/views/forums/index.html.haml_spec.rb
to reduce memory usage. We're using Scout instead now.
> Remove newrelic

- app/controllers/application_controller.rb
- app/controllers/charts/gardens_controller.rb
- app/controllers/data_controller.rb
- app/controllers/gardens_controller.rb
- app/controllers/harvests_controller.rb
- app/controllers/plantings_controller.rb
- app/controllers/seeds_controller.rb
- config/routes.rb
- spec/controllers/charts/gardens_controller_spec.rb
- spec/controllers/gardens_controller_spec.rb
- spec/controllers/harvests_controller_spec.rb
- spec/routing/gardens_routing_spec.rb
- spec/routing/harvests_routing_spec.rb
- spec/routing/member_routing_spec.rb
- spec/routing/plantings_routing_spec.rb
- spec/routing/seeds_routing_spec.rb
this seems to be intended by the models having slugs (added about 7 years ago) but the routes weren't using them
copied from #2320
> Routes using slugs (instead of ids)

- app/models/comment.rb
- app/models/harvest.rb
- app/models/like.rb
- app/models/photo.rb
- app/models/photo_association.rb
- db/migrate/20191226024813_crop_harvest_counter_cache.rb
- db/migrate/20191226024957_crop_photo_counter_cache.rb
- db/migrate/20191226025124_plant_part_harvest_counter_cache.rb
- db/migrate/20191226025225_post_comment_counter_cache.rb
- db/schema.rb
> Adding more counter caches

- Guardfile
- Rakefile
- app/controllers/crops_controller.rb
- bin/bundle
- bin/rails
- bin/rake
- bin/setup
- bin/update
- bin/yarn
- config.ru
- db/migrate/20191226024957_crop_photo_counter_cache.rb
- script/rails
> small file fixes

- app/models/concerns/member_flickr.rb
- app/models/concerns/member_newsletter.rb
- app/models/concerns/search_crops.rb
- app/models/concerns/search_harvests.rb
- app/models/concerns/search_photos.rb
- app/models/concerns/search_plantings.rb
- app/models/concerns/search_seeds.rb
reducing our elastic search usage
> approved crops only, and only 1 shard

- app/models/concerns/search_crops.rb
- app/models/concerns/search_harvests.rb
- app/models/concerns/search_photos.rb
- app/models/concerns/search_plantings.rb
- app/models/concerns/search_seeds.rb
temporarily while we work out how to reduce our Elastic search usage
> Turn off Replicas

- app/models/concerns/predict_planting.rb
- app/models/planting.rb
- spec/models/planting_spec.rb
[WIP]
Closes https://github.com/Growstuff/growstuff/issues/2373
Age in days method now checks if the planting is already finished. It also removes the same method from the model - since it was later redefined in a concern. Since that is newer code, I assumed it should have been cleaned up.
> Progress counter stops if planting is finished

- .travis.yml
- app/views/seeds/_card.html.haml
Travis-ci build is broken with errors about postgresql not running.
I went to the dev branch and re-ran a buld that was fine last week, and now it's also broken with no porgresql. Some thing has changed somewhere.
> Fix travis

- app/controllers/members_controller.rb
- app/views/members/_full_summary.html.haml
- app/views/members/show.html.haml
add plantings status to the member profile page
> Show member plantings summary on member page

- app/views/members/_full_summary.html.haml
* Show member plantings summary on member page
* Remove reference to current member
* Tidy up member planting progress section
> Member planting progress (#2437)

- spec/models/ability_spec.rb
- spec/models/alternate_name_spec.rb
- spec/models/authentication_spec.rb
- spec/models/comment_spec.rb
- spec/models/crop_companion_spec.rb
- spec/models/crop_spec.rb
- spec/models/follow_spec.rb
- spec/models/garden_spec.rb
- spec/models/harvest_spec.rb
- spec/models/notification_spec.rb
- spec/models/photo_spec.rb
- spec/models/planting_spec.rb
- spec/models/post_spec.rb
- spec/models/role_spec.rb
- spec/models/scientific_name_spec.rb
- spec/models/seed_spec.rb
- spec/services/crop_search_service_spec.rb
Auto corrected by following Lint Ruby RSpec/DescribedClass
Click [here](https://awesomecode.io//repos/Growstuff/growstuff/lint_configs/ruby/26858) to configure it on awesomecode.io
> Auto corrected by following Lint Ruby RSpec/DescribedClass

- spec/features/admin/forums_spec.rb
- spec/features/cms_spec.rb
- spec/features/crops/crop_detail_page_spec.rb
- spec/features/harvests/harvesting_a_crop_spec.rb
- spec/features/places/searching_a_place_spec.rb
- spec/features/plantings/planting_a_crop_spec.rb
- spec/features/seeds/misc_seeds_spec.rb
- spec/features/signin_spec.rb
- spec/features/signout_spec.rb
- spec/features/signup_spec.rb
Auto corrected by following Lint Ruby Capybara/CurrentPathExpectation
Click [here](https://awesomecode.io//repos/Growstuff/growstuff/lint_configs/ruby/28718) to configure it on awesomecode.io
> Auto corrected by following Lint Ruby Capybara/CurrentPathExpectation

- spec/requests/conversations_spec.rb
- spec/requests/garden_types_spec.rb
Auto corrected by following Lint Ruby Rails/HttpStatus
Click [here](https://awesomecode.io//repos/Growstuff/growstuff/lint_configs/ruby/25545) to configure it on awesomecode.io
> Auto corrected by following Lint Ruby Rails/HttpStatus

- .codeclimate.yml
- .scss-lint.yml
- Gemfile
- Gemfile.lock
> Bumping rubocop to 0.81

- app/helpers/crops_helper.rb
- app/models/ability.rb
- config/initializers/devise.rb
- db/seeds.rb
- spec/lib/haml/filters/growstuff_markdown_spec.rb
Auto corrected by following Lint Ruby Lint/RedundantCopDisableDirective
Click [here](https://awesomecode.io//repos/Growstuff/growstuff/lint_configs/ruby/9221) to configure it on awesomecode.io
> Auto corrected by following Lint Ruby Lint/RedundantCopDisableDirective

- Gemfile
- Gemfile.lock
- config/application.rb
- config/initializers/jsonapi_resources.rb
Open up the public api for people to build apps on.
I've been tinkering with glitch: https://growstuff.glitch.me/  They have a nice culture of supporting people to build javascript app, which matches the early days of growstuff.
and we need to allow requests by ajax to our API to allow this.
> Api cors headers
