- db/seeds.rb
This is something @pozorvlak mentioned would make sense. Seems sensible to run `load_paid_account_types` and `load_products` in staging, but what about the users? ( @Skud )
> don't load test and admin users in staging

- app/controllers/comments_controller.rb
- app/helpers/application_helper.rb
- app/views/home/_crops.html.haml
In response to [this bug](http://talk.growstuff.org/t/please-test-rails-4/173/28).
It seems the issue is that the `cache_key_for` method (defined in ApplicationHelper) always returns the same key if the same class is passed into it, so I've added an additional argument which can be included in the key to make it uniquely identifying. As it stands the key is generated by looking at the model name, the total count of records for that model and the time of the most recently updated record. If any of those change, the key is refreshed.
I turned caching on in development and this fix appears to work.
I might suggest making a separate story to rip out all this caching stuff and then rebuild it based on New Relic stats.
> Fix cache key

- app/assets/stylesheets/overrides.css.less
- app/views/crops/_thumbnail.html.haml
- app/views/home/_crops.html.haml
- app/views/home/_members.html.haml
- app/views/photos/_thumbnail.html.haml
Mostly just tweaking the display of crops on the homepage, now that the column spacing is different
- made columns 8/4 rather than 6/6
- show 8 interesting crops, not 12
- show 6 recent plantings, not 4
- use crop thumbnail with visible name/info/etc, rather than popup version
- fix up some thumbnail CSS
- made members display 2 across not 3 across
- made some variations to what's shown on mobile screens (now: crops, which have clickable links, and were previously supressed)
Screenshot shows how it looks:
> Release7 tweaks

- CONTRIBUTORS.md
We've lost @jcaudle as a committer :-(
But we've gained @tygriffin :-)
This PR updates CONTRIBUTORS.md with the current list of committers.
> Update CONTRIBUTORS.md with the current committers

- .travis.yml
- Gemfile
- Gemfile.lock
- script/heroku_maintenance.rb
This is (I think) an improvement over #661 in two ways:
- it caches the results of `bundle install`, speeding up builds by a factor of around 2.5
- it doesn't install the whole Heroku toolbelt, which felt like overkill.
It turns maintenance mode on for deployment (and off again afterwards!), but doesn't try to update the environment variables on the Heroku dyno. It also duplicates the branch => app name logic, which is ugly. Perhaps we could parse .travis.yml in `heroku_maintenance.rb`? **Edit** fixed in 5755245.
> Deployment from Travis containers

- lib/tasks/growstuff.rake
fix the deploy task for standard weights feature
> make the one-off save the si weight

- spec/features/planting_reminder_spec.rb
In #420 we found that we weren't able to test links due to the host defaulting to www.example.com. Turns out that since this spec isn't a mailer spec, but a feature spec, we aren't using the default host as configured for ActionMailer in test.rb. 
Here's the bit in the RSpec code that retrieves the default host: 
https://github.com/rspec/rspec-rails/blob/master/lib/rspec/rails/example/feature_example_group.rb#L18 
Unfortunately, I wasn't able to find a way to configure it in test.rb. Any other option seemed to affect everything else. So, I decided to override the feature spec instead, since it will only affect the spec.
> Allow the planting reminder spec to test links in emails properly

- app/controllers/crops_controller.rb
- app/mailers/notifier.rb
- app/models/ability.rb
- app/models/crop.rb
- app/views/crops/_form.html.haml
- app/views/crops/edit.html.haml
- app/views/crops/new.html.haml
- app/views/crops/show.html.haml
- app/views/crops/wrangle.html.haml
- app/views/notifier/crop_request_approved.html.haml
- app/views/notifier/crop_request_rejected.html.haml
- app/views/notifier/new_crop_request.html.haml
- db/migrate/20150130224814_add_requester_and_approved_to_crops.rb
- db/migrate/20150130224814_add_requester_to_crops.rb
- db/migrate/20150201053200_add_approval_status_to_crops.rb
- db/migrate/20150201062506_add_reason_for_rejection_to_crops.rb
- db/migrate/20150201064502_add_request_notes_to_crops.rb
- db/schema.rb
- spec/controllers/crops_controller_spec.rb
- spec/factories/crop.rb
- spec/features/crops/crop_wranglers_spec.rb
- spec/features/crops/request_new_crop_spec.rb
- spec/mailers/notifier_spec.rb
- spec/models/ability_spec.rb
- spec/views/crops/wrangle.html.haml_spec.rb
Fixes #602
**WIP: Needs feedback**
1. Is the language natural enough for regular members on the new crops form page?
2. Should we use Javascript to pop up the reason for rejection only when `approval_status` is "rejected" on the edit crops form?
3. Is the `reason_for_rejection` required if rejected?
4. Should the reasons for rejection be hardcoded in the model or should they be in a database table? (Database seems to make more sense. That way, if a wrangler selects "other" as a reason, wranglers can be presented the option to create a new reason.)
5. How should we avoid race conditions? Should we simply prevent a wrangler from marking a crop rejected if it's already approved and vice versa - with a descriptive error message?
6. Should it be impossible to navigate to rejected crop by going …
> Crop request

- app/controllers/crops_controller.rb
- app/mailers/notifier.rb
- app/models/ability.rb
- app/models/crop.rb
- app/models/harvest.rb
- app/models/planting.rb
- app/models/seed.rb
- app/validators/approved_validator.rb
- app/views/crops/_form.html.haml
- app/views/crops/show.html.haml
- app/views/crops/wrangle.html.haml
- app/views/notifier/_signature.html.haml
- app/views/notifier/crop_request_approved.html.haml
- app/views/notifier/crop_request_rejected.html.haml
- app/views/notifier/new_crop_request.html.haml
- app/views/notifier/notify.html.haml
- app/views/notifier/planting_reminder.html.haml
- db/migrate/20150209105410_add_rejection_notes_to_crops.rb
- db/schema.rb
- spec/features/crops/request_new_crop_spec.rb
- spec/mailers/notifier_spec.rb
Addresses many of the issues that @Skud mentioned in [this Talk testing thread](http://talk.growstuff.org/t/please-test-requesting-new-crops-new-seed-attributes/223/3)
Some issues remain outstanding however:
> I'm able to go back into a previously-rejected crop and make it pending again, which I suppose isn't a big problem, but when I do so and then visit the crop page it says "This crop was requested by on February 09, 2015 at 05:23." -- note that the requester's name is missing, and also I think it should use the "ago" notation for the date, eg. "2 hours ago".
I didn't notice the missing requester's name.
> I'm getting an intermittent "something went wrong" error when trying to approve/reject/etc ... I thought at first it occurred when I tried to approve something and give a reason for …
> Fix request new crop

- app/views/alternate_names/show.html.haml
- app/views/crops/_approval_status_message.html.haml
- app/views/crops/show.html.haml
- app/views/scientific_names/show.html.haml
- spec/features/crops/alternate_name_spec.rb
- spec/features/scientific_name_spec.rb
Fixes no. 10 from this [testing thread on Talk](http://talk.growstuff.org/t/please-test-requesting-new-crops-new-seed-attributes/223/17?u=tygriffin)
>As a crop wrangler: scientific names and alt names belonging to pending or rejected crops aren't visibly marked as such when you visit their pages. There should be a red warning at the top, same as for crops.
> Pending rejected sci alt names

- Gemfile
- Gemfile.lock
Poltergeist v1.5.1 is nearly a year old, and relies on PhantomJS 1.8, which is 2.5 years old and increasingly hard to find in OS package managers. Poltergeist v1.6 [claims to work with PhantomJS >= 1.8.1](https://github.com/teampoltergeist/poltergeist#installing-phantomjs); I've tested it with PhantomJS 2.0.0 and it runs our test suite without complaint.
> Upgrade poltergeist to v1.6.

- app/assets/javascripts/crops.js.erb
- app/assets/stylesheets/overrides.css.less
- app/views/crops/_hierarchy.html.haml
- app/views/crops/_varieties.html.haml
- spec/features/crops/crop_detail_page_spec.rb
Please review.
Implemented #621 with javascript as I didn't realize rails-y implementation was preferred over javascript here and I wanted the toggle to look smooth instead of refreshing the whole page.
Let me know if you want me to rewrite using different technology etc.
Thanks!
> #621 Crop varieties sidebar

- spec/factories/crop.rb
- spec/features/plantings/planting_a_crop_spec.rb
Not linked to an issue, just trying to increase our Coveralls stats as a break from the deletion work.
> More tests

- db/seeds.rb
- db/seeds/suburbs.csv
Made some improvement on the database seeding process, covering some items from issue #578. Just did this as I wanted to test performance on geo related processing.
This will let you...
- Create N number of members and 
- Populate member's location
- Populate garden's location
- Creates a planting from various crops, sunniness and planted_from for each user.
The default number of members is still 3, but you can specify the number of members as...
<code>rake db:seed member_size=100</code>
or
<code>rake db:reset member_size=100<code>
Tested up to 1000 worked fine.
> #578 More extensive database seeding - bulk creating members, gardens and plantings

- CONTRIBUTORS.md
- db/schema.rb
> Moving myself to the committers section

- CONTRIBUTORS.md
- app/controllers/notifications_controller.rb
- app/helpers/notifications_helper.rb
- app/models/ability.rb
- app/views/notifications/_notification.html.haml
- app/views/notifications/reply.html.haml
- app/views/notifications/show.html.haml
- config/routes.rb
- spec/controllers/notifications_controller_spec.rb
- spec/features/notifications_spec.rb
- spec/helpers/notifications_helper_spec.rb
Issue #520 
This PR adds a new action ```reply``` to the ```NotificationsController```. 
The ```reply_link``` for the private message replies is changed to /notifications/:id/reply.
It will render the notification the user is replying to.
> #520 Show private message I'm replying to

- spec/helpers/application_helper_spec.rb
- spec/views/shop/index_spec.rb
Issue #558
I noticed that the application_helper.rb spec file wasn't following the naming conventions. I had to rename it.
> #558 Currency refactoring in specs.

- CONTRIBUTORS.md
- Gemfile.lock
- app/controllers/places_controller.rb
- app/views/places/_search_form.html.haml
- app/views/places/index.html.haml
- app/views/places/show.html.haml
- config/database.yml
- config/environments/test.rb
- config/initializers/geocoder.rb
- spec/features/places/searching_a_place_spec.rb
places#show has a search form but places#index doesn't have. I added a search form in the index page of the 'places' so that the users may easily search the place they want to see.
@pozorvlak Sorry I messed up my last PR. Here is a new one. I left the gitignore untouched this time.
> Added search form on the places index page.

- .gitignore
- CONTRIBUTORS.md
- app/views/comments/_single.html.haml
- app/views/members/_account.html.haml
- app/views/posts/_single.html.haml
- spec/features/comments/commenting_a_comment_spec.rb
- spec/features/posts/posting_a_post_spec.rb
@Skud  this PR is for issues #476 and #546 .
The system changes Posted by <name> on <date/time> into Edited by <name> on <date/time> whenever a post/comment is edited.
> Show edited date/time on posts/comments and Show last login date on member profile

- config/secrets.yml
Currently the staging server is down because it can't find the secret key needed to sign cookies. This is related to the changes in #710.
> Set staging secret key from environment

- script/deploy-tasks.sh
The ElasticSearch index task was run, but failed because we didn't have an ElasticSearch instance to run it against.
There's also a potential speed improvement on the `growstuff:import_crops` rake task. Currently we load the cropbot user once per row, but we could load them once at the beginning. I don't know how much of a speedup this would give. Right now it doesn't matter too much, but we'll no doubt want to add crops in the future (and the same code is run by `rake db:seed`).
> Remove one-off tasks that were run for Release 8.

- app/views/gardens/show.html.haml
- app/views/members/_gardens.html.haml
- app/views/places/show.html.haml
- app/views/plantings/_thumbnail.html.haml
- app/views/plantings/index.html.haml
- spec/features/places/searching_a_place_spec.rb
OLD places page:
NEW places page:
Hi @pozorvlak and @maco ,
I added nearby seeds and plantings in addition to nearby members as a result when searching for a place (see image above). I also created the feature tests on this.
I'll be waiting for your response.
Gabriel Sandoval,
AELOGICA Intern
> Fixes #720 - Places show nearby seeds, members, and plantings.

- app/controllers/application_controller.rb
- spec/features/signout_spec.rb
Sign out redirects to last page visited however, it doesn't redirect to root_path if the page last visited needs authentication (e.g. edit account), instead it is redirected to the login page
> [#568] Signout redirects to last page visited

- CONTRIBUTORS.md
- app/assets/javascripts/seeds.js.coffee
- app/assets/stylesheets/overrides.css.less
- app/controllers/crops_controller.rb
- app/models/crop.rb
- app/views/alternate_names/_form.html.haml
- app/views/crops/_form.html.haml
- spec/features/crops/creating_a_crop_spec.rb
- spec/features/crops/crop_wranglers_spec.rb
- spec/features/crops/request_new_crop_spec.rb
- spec/views/crops/edit.html.haml_spec.rb
- spec/views/crops/new.html.haml_spec.rb
Hi,
I paired with @jacarandang to fix this issue. Here's the new crop page form:
Any say to this?
Gabriel Sandoval, Jym Paul Carandang
AELOGICA Interns
> Added multiple forms for scientific and alternate names on crop creation  (Fixes #615)

- .gitignore
- CONTRIBUTORS.md
- app/assets/stylesheets/overrides.css.less
- app/helpers/application_helper.rb
- app/views/gardens/_form.html.haml
- app/views/harvests/_form.html.haml
- app/views/plantings/_form.html.haml
- app/views/seeds/_form.html.haml
- db/schema.rb
- spec/features/gardens/adding_gardens_spec.rb
- spec/features/gardens_spec.rb
- spec/features/harvests/harvesting_a_crop_spec.rb
- spec/features/plantings/planting_a_crop_spec.rb
- spec/features/seeds/adding_seeds_spec.rb
- spec/helpers/application_helper_spec.rb
Given that users are torn between marking required fields and marking optional fields, I decided to go with both and mark required fields with a red asterisk and denote optional fields with an "optional" placeholder or or used "include_blank: 'optional'" on select fields that previously had "include_blank: true". issue #718
> #718 optional and required fields

- app/assets/stylesheets/overrides.css.less
- app/helpers/gardens_helper.rb
- app/views/home/_members.html.haml
- app/views/members/_thumbnail.html.haml
- app/views/members/index.html.haml
This makes it so the member entries have the same white background as other cards and reflow as the page is resized. In the process, I removed some HTML elements that existed solely for display reasons and not for semantic reasons.
> Correct browser-resize issues with the members section of homepage and make members page match

- app/views/layouts/_footer.html.haml
- spec/features/footer_spec.rb
The graphic provided by [Open Definition](http://opendefinition.org/ossd/) is now displayed on the right of the footer.
Resolves #617
> Resolves #617 - Open Service graphic link in footer

- app/mailers/notifier.rb
People were forgetting to create config/application.yml, which meant that RAILS_SECRET_TOKEN wasn't being set, which meant that all tests involving notifications failed. Unfortunately, the resulting wall of error messages (https://gist.github.com/sha1sum/5debae6b700ff8fc0c76) did not make the root cause remotely clear, leading to much confusion and head-scratching all round.
This commit checks for the existence of RAILS_SECRET_TOKEN and fails with an informative error message if it's missing.
> Check existence of secret token before using it.

- app/views/posts/_summary.html.haml
- spec/views/forums/index.html.haml_spec.rb
Fixes #789 by making dates absolute rather than relative
> Fixing relative caching of post summary on homepage, fixed #789

- app/views/posts/_summary.html.haml
- spec/views/forums/index.html.haml_spec.rb
Reverts Growstuff/growstuff#793 that reverted #790. This one should now validly give the right fix, and since #775 is now sorted, Travis should be happy. So this now needs review from someone who is not me, particularly that we're happy with the UX of dates being absolute rather than relative.
> Fixing #790 properly - caching posts on homepage

- app/views/plantings/_planting_progress.html.haml
See #788 for details - root cause seems to be in plantings progress partial, based on the logs. I couldn't reproduce the error 500 easily locally, so putting this onto staging is probably best to check it achieves the desired result.
> Fix issue #788 with uncaught nil

- app/views/devise/sessions/new.html.haml
Minor usability/mobile UI annoyance - you can't click the 'remember me' text to tick the checkbox.
This:
* Applies bootstrap classes around the checkbox
* Saves my big fat fingers from selecting text when they shouldn't
> Style checkbox for 'remember me' 

- app/views/devise/registrations/_edit_email.html.haml
- app/views/devise/registrations/new.html.haml
Continues #797
The only other ones are in form partials, and don't really have the same kind of label - decided to leave them well enough alone.
> Fix more checkbox labels in registration and email editing

- app/views/layouts/_meta.html.haml
- app/views/layouts/application.html.haml
#733 Add the correct RDFa prefix
I think this will work OK, but don't have a way to test my localhost properly.
http://www.w3.org/2012/pyRdfa/extract tells me it's valid RDFa, producing:
```
@prefix ns1: <http://ogp.me/ns#image:> .
@prefix ns2: <http://www.w3.org/1999/xhtml/vocab#> .
@prefix og: <http://ogp.me/ns#> .
<> og:image "http://localhost:3000/assets/growstuff-apple-touch-icon-precomposed-8e3c5998fc73bde728cfc3a2ea8fb69f.png"@en;
ns1:secure_url "images/growstuff-apple-touch-icon-precomposed.png"@en .
[] ns2:role ns2:navigation .
```
Or in other words, <> (this page) has an og:image of "http://localhost:3000/assets/growstuff-apple-touch-icon-precomposed-8e3c5998fc73bde728cfc3a2ea8fb69f.png"
If this doesn't work, probably need to make it …
> Add correct prefix to fix facebook share icon

- app/helpers/application_helper.rb
- app/views/members/_avatar.html.haml
- app/views/members/_image_with_popover.html.haml
- db/migrate/20150824145414_add_member_preferred_image.rb
- db/schema.rb
- spec/helpers/application_helper_spec.rb
Partially addresses #509 - since most of the oauth providers give you an avatar URI, it'll be trivial to refactor #811 a bit further to set it to your $whatever login pic.
and we simulate the oauth login setting this:
```
irb(main):003:0* m = Member.first; m.preferred_avatar_uri = 'http://media.catmoji.com/post/ujg/cat-in-hat.jpg'; m.save!
Member Load (47.1ms)  SELECT  "members".* FROM "members"   ORDER BY lower(login_name) asc LIMIT 1
Member Load (46.4ms)  SELECT  "members".* FROM "members"   ORDER BY lower(login_name) asc LIMIT 1
(41.5ms)  BEGIN
Member Exists (47.1ms)  SELECT  1 AS one FROM "members"  WHERE (LOWER("members"."login_name") = LOWER('daniel_oconnor') AND "members"."id" != 8) LIMIT 1
SQL (43.5ms)  UPDATE "members" SET "preferred_avatar_uri" = $1, "updated_at" = $2 WHERE …
```
> Add member preferred image

- app/views/layouts/_header.html.haml
- spec/features/admin/account_types_spec.rb
- spec/features/admin/forums_spec.rb
- spec/features/crops/alternate_name_spec.rb
- spec/features/crops/crop_detail_page_spec.rb
- spec/features/crops/crop_wranglers_spec.rb
- spec/features/footer_spec.rb
- spec/features/locale_spec.rb
- spec/features/member_profile_spec.rb
- spec/features/rss/comments_spec.rb
- spec/features/rss/crops_spec.rb
- spec/features/rss/members_spec.rb
- spec/features/rss/plantings_spec.rb
- spec/features/rss/posts_spec.rb
- spec/features/rss/seeds_spec.rb
- spec/features/scientific_name_spec.rb
- spec/features/seeds/misc_seeds_spec.rb
- spec/features/signin_spec.rb
- spec/features/signup_spec.rb
Another attempt at turning on Javascript for more of our tests. Based on #670 by @pozorvlak, with a few further fixes. Ready for merge - all tests passing.
> Turn on Phantom JS for all tests

- lib/haml/filters/growstuff_markdown.rb
- spec/lib/haml/filters/growstuff_markdown_spec.rb
Lookahead in markdown to verify \ is not present
Test for escaping crop link
Fixes #721
> Fix #721 : Escape quick crop link in markdown

- app/views/gardens/show.html.haml
- app/views/members/_gardens.html.haml
Also rearrange some of the headings (sizing) and controls (add new garden) to be more clearly not a tab.
Also the same type of fixes and some basic layout tweaks on the show garden UI:
> Fix #818 by removing the .thumbnail around the button.

- Gemfile
- Gemfile.lock
- config/application.yml.example
- spec/rails_helper.rb
Adds the ability to run feature tests via selenium if you configure it;
or run specs with ```GROWSTUFF_CAPYBARA_DRIVER=selenium bundle exec rake spec:features/```
I find this really useful because:
* You can actually see what's going on
* Combined with pry; you can interactively debug the current browser window and resolve issues with visibility
* Its possible to test against multiple browsers with a bit of configuration
Defaults to poltergeist still for CI, normal use
> Add additional capyabara driver options

- Gemfile
- Gemfile.lock
https://github.com/DatabaseCleaner/database_cleaner/pull/364 resolves an issue where database_cleaner gets upset by open transactions; often in the way that Capybara keeps a few open on modern rails.
This upgrades us to the latest:
https://rubygems.org/gems/database_cleaner/versions/1.5.0
> Upgrade database cleaner gem

- spec/views/forums/index.html.haml_spec.rb
Hello, this spec do not respect timezones, and fails depending on the time of the day I run.
More info: http://www.elabs.se/blog/36-working-with-time-zones-in-ruby-on-rails
> Fixing a spec timezone problem.

- app/views/alternate_names/show.html.haml
- app/views/scientific_names/show.html.haml
- spec/views/scientific_names/show.html.haml_spec.rb
Scientific names:
Only show edit links if we have permission
Alternate names:
Don't show a pipe if we only have one option
> Tweak permissions links

- app/helpers/harvests_helper.rb
Harvest description headings: Issue [#852](https://github.com/Growstuff/growstuff/issues/852) 
I checked out the harvest index view, and it was using the display_harvest_description method in harvests_helper.rb, which looked like this: 
```  
def display_harvest_description(harvest)
if harvest.description.nil?
"No description provided."
end
```
But the view wasn't displaying "No description provided", it just displayed the heading. There were two options with this, I could remove the panel and heading entirely when there's no description, or fix the method that was already there. I went with the latter because I noticed the individual harvest view pages also render "No description provided" for no description, and so I changed the method to ```if harvest.description.empty?``` since when …
> #852 Harvest description headings rendered when there's no description

- spec/controllers/member_controller_spec.rb
```
WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives, since `raise_error` will match when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the expectation to pass without even executing the method you are intending to call. Actual error raised was #<ActiveRecord::RecordNotFound: Couldn't find Member with 'id'=9999>. Instead consider providing a specific error class or message. This message can be supressed by setting: `RSpec::Expectations.configuration.warn_about_potential_false_positives = false`. Called from /home/travis/build/Growstuff/growstuff/spec/controllers/member_controller_spec.rb:65:in `block (3 levels) in <top (required)>'
WARNING: Using the `raise_error` matcher without providing a …
```
> Fix WARNING: Using the `raise_error` matcher without providing a specific error

- .travis.yml
Previously we were only installing the gems needed for testing. This caused our CI to miss an incompatibility problem with a gem that was only needed for another environment:
https://github.com/Growstuff/growstuff/pull/878#discussion_r63745751
> Install *all* gems in TravisCI

- app/views/harvests/_form.html.haml
The warning was
app/views/harvests/_form.html.haml:32: warning: duplicated key at line 32 ignored: :class
We were specifying two `:class` attributes on an HTML tag; I've combined them into one.
> Fix "duplicated key: :class" warning in HAML code

- app/assets/stylesheets/overrides.sass
- app/views/members/_gardens.html.haml
- app/views/places/show.html.haml
- app/views/plantings/_thumbnail.html.haml
- app/views/plantings/show.html.haml
Fixes #870
Before:
http://growstuff.org/plantings/
After:
I haven't checked this on mobile yet, and the fixed-width behaviour I used to style the definition list feels wrong (on the other hand, the previous styling also used fixed widths)
> Improve the styling of a planting to be more like the other card-layouts

- app/assets/stylesheets/custom_bootstrap/variables.sass
Fixes #896 
And Lea Verou's contrast checker says this is WCAG 2.0 compliant.
> darken navbar item text when it opens (and the background turns light)

- .codeclimate.yml
- Gemfile
- README.md
- spec/spec_helper.rb
Our code climate score is *abysmal*, but now that I've been using it in my job for a few months, I have some ideas how to improve it. It's all about clean code (check out the book of that name from your local library) and readability. So let's add the grade to the README, and I'll figure out how to set up Code Climate to work with Travis CI.
> Add code climate to README

- Gemfile.lock
- config/factory_girl.rb
* commit updated Gemfile.lock for Code Climate inclusion
* add config/factory_girl.rb so that rspec doesn't fail with a confusnig
'Could not find mapping for #<Member...' error
http://blog.thefrontiergroup.com.au/2011/03/reloading-factory-girl-factories-in-the-rails-3-console/
The former is why my photo PR is failing.
The latter happens when you make significant changes to a controller then re-run rspec. It's a Factory Girl / rspec caching issue. It's only a problem for devs running rspec locally, not Travis.
> Fix two small things (including: make tests stop failing)

- app/assets/stylesheets/overrides.sass
> set background color on autocomplete dropdown. Fixes #914

- app/views/comments/index.html.haml
- app/views/crops/show.html.haml
- app/views/crops/wrangle.html.haml
- app/views/gardens/index.html.haml
- app/views/harvests/index.html.haml
- app/views/members/index.html.haml
- app/views/members/view_followers.html.haml
- app/views/members/view_follows.html.haml
- app/views/photos/index.html.haml
- app/views/photos/new.html.haml
- app/views/plantings/index.html.haml
- app/views/posts/index.html.haml
- app/views/seeds/index.html.haml
- config/locales/en.yml
Use translation template to set singular/other strings
for .model_name
Fixes #855 
And I'm about to go file bugs regarding us doing things like `pluralize(member.posts.size, "post")` that result in untranslated text
> Stop hard-coding strings for pagination

- spec/features/crops/crop_detail_page_spec.rb
- spec/features/gardens_spec.rb
- spec/features/planting_reminder_spec.rb
Fixes the "rspec output includes an HTML page dump" issue noted at
https://github.com/Growstuff/growstuff/commit/2089866756f8c42c8c582f33ceccbeb0585df141#diff-6464240396bc745d7e89a408c200fd3aR15
> Remove warnings and debugging puts from rspec output

- spec/rails_helper.rb
SimpleCov was reporting 0% coverage for any files loaded before `SimpleCov.start` was called, even if they were fully tested. This patch loads the application *after* starting SimpleCov, leading to more accurate coverage figures.
> Fix coverage calculations

- Gemfile
- Gemfile.lock
Fixes #953
This is the release just after what we had previously pinned
https://github.com/alexreisner/geocoder/commit/104d46 is roughly release 1.1.9
>  Swap to geocoder 1.1.9

- app/controllers/application_controller.rb
This should eliminate the screens-ful of deprecation warnings when running the test suite.
> Replace deprecated Devise `for` method with `permit`

- spec/rails_helper.rb
Plain and simple. Removing the deprecation warning while running tests:
`<top (required)>': [DEPRECATION] ::[] is deprecated. Use ::new instead.`
> Fix SimpleCov Deprecation Warning

- config/application.rb
We were actually trying to send from the local server instance's install of sendmail
> don't override our environment email settings with plain old sendmail

- spec/rails_helper.rb
[StackOverflow](http://stackoverflow.com/a/36003988) and [GitHub commenters](https://github.com/teampoltergeist/poltergeist/issues/375#issuecomment-42620085) suggested that this might help with our intermittent "Request to http://localhost:8081 failed to reach server, check DNS and/or server status" errors in CI - the theory being that the error message is misleading, and it's actually a daughter request to an external service timing out. Seems worth a shot. It also ought to speed up testing, but the effect is slight (10s out of 3.5 minutes) on my machine.
I've blacklisted the URLs I could find in app/views or by tcpdumping a test run, because I couldn't get URL whitelisting to work.
> Block external URLs in feature tests

- .travis.yml
- script/gemfile_check
Quick-and-dirty script to catch an error we've missed a couple of times in code review, but which is not (AFAICT) covered by any of our existing checkers. Inspired by the following posts:
- https://zachholman.com/posts/how-github-writes-blog-posts/
- https://zachholman.com/talk/move-fast-break-nothing/
> Check for "forgot to commit Gemfile.lock" in CI

- CONTRIBUTORS.md
- README.md
Changed reference to "Freenode" to "irc.freenode.net" in README.md for clarification for newcomers to IRC.
> issue #1006: change "Freenode" to "irc.freenode.net" in README.md

- app/views/layouts/_header.html.haml
On small screens, the search bar in the heading reflows poorly so that some content is inaccessible.
This change puts it under the collapsible menu on smaller screens, which is a lot neater.
> Use navbar-right, and reposition search box to fix mobile layout

- CONTRIBUTORS.md
- app/assets/stylesheets/overrides.sass
- app/views/layouts/_header.html.haml
Hi. I enhanced the search bar by adding a button on the side to make it more efficient to the users.  Here's how it looks like. 
I also made the logo of the site responsive in the mobile view so that the search bar can also be accessible. Here it is in mobile view:
> Enhancement of the navigation bar (header)

- CONTRIBUTORS.md
- app/controllers/registrations_controller.rb
- app/controllers/sessions_controller.rb
I wanted to sign in/out over the json API. I told devise to allow repsonding in json in both registration and session controller.
There might be another way to do this already, but the API docs link in the readme is all 404-ed pages.
> allow registration and signin/out on the API

- CONTRIBUTORS.md
- app/views/harvests/_thumbnail.html.haml
- spec/features/harvests/browse_harvests_spec.rb
I found it confusing that "bob's harvest" doesn't link to Bob's harvest. It instead links to Bob. I've made this mistake many times trying to get a the harvest#show from harvest#index.
This patch makes that link lead to the harvest itself.
> harvest thumbnail title linking to the harvest itself

- app/views/gardens/_thumbnail.html.haml
"[Member]'s garden" should link to the garden, not the member
> Bugfix: Link to garden, not member

- app/models/crop.rb
- spec/models/crop_spec.rb
the regexp was missing a \z t end it, so allowed anything you want afterwards. 
These are handled safely afterwards, but the regex still needed a fix.
> Narrow-ed regex on wikipedia url

- spec/factories/comments.rb
We had an inline comment that had been split over two lines; whitespace fixes made this look very weird.
Followup to #1072.
> Fix comment-style weirdness

- lib/tasks/testing.rake
Previously, `rake spec` ran the tests whether or not the `growstuff_test` database existed or not, but `rake` crashed unless it had already been created. The problem was that `rake` was trying to load the environment, which required the presence of a DB; `rake spec` was running this with the `dev` environment, so succeeded if `growstuff_dev` existed, but `rake` was running everything with the `test` environment, so would fail if `growstuff_test` did not exist.
This patch adds `db:create` to the dependencies of the `spec` task, forcing an unadorned `rake` to create all necessary databases first.
tl;dr you should now be able to just type `rake` to run specs locally.
> Run tests with `rake` when DB does not yet exist

- .travis.yml
- config/environments/test.rb
According to https://github.com/teampoltergeist/poltergeist/issues/677#issuecomment-222919584, a possible cause of the "Request failed to reach server" problem (#901) is that assets are being compiled on-demand, causing enough of a slowdown for PhantomJS to think the connection has failed. This PR turns off lazy asset compilation in the test environment and precompiles assets before testing on Travis.
We should also turn off lazy asset compilation in production - see http://stackoverflow.com/questions/8821864/config-assets-compile-true-in-rails-production-why-not Our Heroku deployments already run `rake assets:precompile`.
> Precompile assets in test

- app/helpers/plantings_helper.rb
- spec/helpers/plantings_helper_spec.rb
- fixes the bug that caused #1079
- fixes an off-by-one error in the calculation
- always return a string from the helper.
I'm not totally sold on 589a31d; it's possible I've spent too much time coding in statically-typed languages recently and that this isn't an issue in Ruby. But it tripped me up while working on the other two commits.
> Fix PlantingHelper.display_days_before_maturity

- app/constants/photo_models.rb
- app/controllers/photos_controller.rb
- app/models/concerns/photo_capable.rb
- app/models/garden.rb
- app/models/harvest.rb
- app/models/photo.rb
- app/models/planting.rb
- spec/models/photo_spec.rb
* move stuff in models into a concern
* create combined collection for all models that have photos
I'm marking this WIP because I think a constants file that maps garden/gardens/Garden would make it possible to minimize repetition in `photos_controller.rb` too. I want to minimize how many places we need to touch on adding a new model-that-uses-photos because I know missing a copy&paste has introduced bugs before. (The particular past bug I'm thinking of is handled by this commit, though, with the `self.destroy unless relationships.size > 0`)
> DRY up photo & model interaction

- app/models/crop.rb
because some have - or () in name
example:
- https://en.wikipedia.org/wiki/Urad_(bean)
- https://en.wikipedia.org/wiki/Curry-leaf_Tree
(Fixes: #1104)
> expand wikipedia regex to include -, (, and )

- .travis.yml
Travis is getting 403s from the phantomjs download url
it's still the same url found on the phantom project page
http://phantomjs.org/download.html
but to keep travis running, here's a revert back to the old url
> Revert "Changed phantomjs url to project official"

- .codeclimate.yml
Code Climate really doesn't like that it's minified
> ignore the minified bootstrap accessibility file for code climate checks

- app/constants/photo_models.rb
- app/models/seed.rb
- db/migrate/20161201154922_add_photos_seeds_table.rb
- db/schema.rb
Fixes #495 
untested, waiting on #1106 and #1107
> add photos to seeds

- app/models/crop.rb
wikipedia urls can have a fullstop on them. Infact we have one in our db:seeds
https://en.wikipedia.org/wiki/Capsicum_annuum_var._glabriusculum
> Yet another wikipedia url char added to regex

- app/models/member.rb
- lib/geocodable.rb
- spec/features/signin_spec.rb
- spec/models/crop_spec.rb
- spec/models/member_spec.rb
- spec/models/post_spec.rb
Adds some unit tests for posts and crops, and does some slight cleanup of the existing tests there. Also adds one feature test for "sign-in using email address rather than username", because that works by implementing a callback for Devise to use, and it didn't seem that unit-testing the callback was very worthwhile: the callback is trivial, the question is whether it matches Devise's expectations.
The two models with big coverage gaps are Member and Photo, because of the code to talk to Gibbon and Flickr. We could (and perhaps should) get those coverage numbers up with some judicious mocking. **Edit**: I've made a start at this.
The directory with the worst coverage is hands-down `app/controllers`, some of whose members have *dire* coverage. We deprecated controller tests a while back in …
> Improve unit test coverage for models

- app/helpers/gardens_helper.rb
- app/views/gardens/_thumbnail.html.haml
- app/views/members/_gardens.html.haml
uses the garden's name in the link to the garden.
also truncates it to 50 chars, because really long names muck with the display on many pages.
this was one of the changes in #1123
> Garden's name in link

- app/controllers/crops_controller.rb
- app/models/notification.rb
- lib/tasks/growstuff.rake
Production (and my dev) is crashing out on a sys.exit at:
* new crop request / approval
* following another user
* planting reminders
this changes to deliver_now
> change deliver_later to deliver_now, so we don't sys.exit() crash

- Gemfile
It was only being installed in development and test environments, causing deployment failures.
Fixes #1170
> Install d3-rails gem in production and staging

- app/controllers/gardens_controller.rb
- app/controllers/members_controller.rb
- app/views/gardens/_nav.haml
- app/views/gardens/index.html.haml
- app/views/members/_gardens.html.haml
- app/views/members/show.html.haml
- app/views/plantings/_nav.haml
- spec/features/gardens_spec.rb
same as #1141 
Show active gardens by default (unless the show inactive is checked)
This also changes the button labels to match plantings more.. e.g "Everyone's gardens" instead of "View everyone's gardens".
> hide inactive gardens by default

- CONTRIBUTORS.md
This prevents deppbot-generated pull requests from failing the "are you in CONTRIBUTORS.md?" check in CI.
I, for one, welcome our new robot overlords.
> Add deppbot to CONTRIBUTORS.md

- README.md
Instead of showing the most recent buid (on any branch),
show the dev branch.
Fix for my mistake in #1271
> Tie travis badge to a branch

- app/controllers/gardens_controller.rb
This page is linked to from the front page: 
http://www.growstuff.org/gardens
and shows all gardens
it is ordered by name - and the first page is gardens that haven't been planting in for 4 years.
This PR changes that to order by :updated_at, resulting in a page full of active gardens.
> Gardens order

- README.md
- app/views/crops/_form.html.haml
- app/views/notifier/new_crop_request.html.haml
and adding one link to github issues.
part of #1193
> Removing references to Discourse (talk.growstuff.org)

- app/assets/stylesheets/overrides.sass
- app/helpers/gardens_helper.rb
- app/views/gardens/_thumbnail.html.haml
- spec/helpers/gardens_helper_spec.rb
Puts the `<li>` inside a `<ul>`
adds a class to the `<ul>`
turns off the bullets  in `ul.plantings`
Moves the number `2` from being in two far apart files, to instead being on subsequent lines in the same file. This is better connascence. (It's only called in this one place)
Added `.includes(:crop)` to reduce query count
Updated specs
before:
after:
> Garden thumbnail display cleanup

- app/views/photos/new.html.haml
- config/routes.rb
This puts a route in, where omniauth-flickr seems to want it, since the release 14 gem updates that broke it.
I don't have facebook, so someone else checking the facebook auth still works is a good idea.
> Route for flickr auth callback -- Fixes  #1106

- app/models/seed.rb
- app/views/home/_seeds.html.haml
- spec/views/home/_seeds.html.haml_spec.rb
Display seeds for trade, on homepage, as thumbnails.
Note: there is an existing seeds/_thumbnails template, but it's not really a thumbnail.
Fixed #1334  for seeds
> Display seeds for trade, on homepage, as thumbnails.

- app/controllers/gardens_controller.rb
- app/models/garden.rb
- app/models/planting.rb
- app/views/gardens/show.html.haml
- app/views/members/_gardens.html.haml
- app/views/places/show.html.haml
- app/views/plantings/_card.html.haml
- app/views/plantings/_thumbnail.html.haml
- app/views/plantings/index.html.haml
- spec/views/gardens/show.html.haml_spec.rb
Shrink the inactive plantings down to thumbnails
This renames the existing "plantings/thumbnail" to be "plantings/card". This makes more sense to me, because it wasn't really a thumbnail.
> Inactive plantings show as tiny thumbnails

- app/views/gardens/_actions.html.haml
- app/views/gardens/show.html.haml
- app/views/plantings/show.html.haml
- spec/features/photos/new_photo_spec.rb
- spec/views/gardens/show.html.haml_spec.rb
In the planting and garden show views, I added an extra 'Add photo' button next to the other actions. I didn't get rid of the original add photo buttons as I thought it would be easier for users just to have another option. I'm definitely open to styling or button placement changes.
fixes #1450
> Fixes #1450 Adds a more prominent add photo button to garden and planting show views

- app/views/gardens/_actions.html.haml
- app/views/plantings/_actions.html.haml
- app/views/plantings/show.html.haml
- spec/features/gardens/gardens_index_spec.rb
A bug slipped into all garden display pages - and there were no tests that caught it.
This adds feature specs for gardens#index, which would have detected the un-initialised
variable in haml
> Fix gardens actions, and add specs

- .travis.yml
Fixes #1099, or at least works around it, though a better solution would be to rewrite our deployment system using Travis build stages or Heroku build pipelines.
This should reduce a lot of our problems with failed "dev" builds - currently, we're getting failures because two jobs try to deploy the same commit, and the second deployment is rejected.
The Elasticsearch job was picked because it's the one most likely to fail, and I can't work out how to deploy only if all three jobs pass.
> Only deploy from the Elasticsearch build job

- db/migrate/20180118112809_add_datetaken_to_photos.rb
fix for #1581
We can run the update of photos.date_taken manually
> Don't update flickr photos in migration

- app/helpers/photos_helper.rb
- app/models/crop.rb
- app/views/crops/_index_card.html.haml
- app/views/crops/_thumbnail.html.haml
- app/views/gardens/_photo.html.haml
- app/views/gardens/_thumbnail.html.haml
- app/views/harvests/_card.html.haml
- app/views/harvests/_thumbnail.html.haml
- app/views/plantings/_card.html.haml
- app/views/plantings/_thumbnail.html.haml
- app/views/seeds/_card.html.haml
- app/views/seeds/_thumbnail.html.haml
- spec/helpers/photos_helper_spec.rb
Moved photo image selection all into one file. Removes a lot of repeating code and then let me tidy up photo selection.
The photo for seeds was different on the #show and #index and home page. This makes it always the same. 
Also tidied up crop photo selection to look on planting, harvests, and then seeds. 
Added unit tests of the helpers.
> Use photos helpers to find photos

- CONTRIBUTORS.md
- app/assets/stylesheets/overrides.sass
- app/views/seeds/index.html.haml
Fixes weird wrapping on `/seeds` and `/members`. I didn't see the issue on the homepage or `/gardens#index`
https://github.com/Growstuff/growstuff/issues/1459
> Fix various wrapping issues

- app/assets/stylesheets/overrides.sass
- app/views/posts/show.html.haml
Fixes https://github.com/Growstuff/growstuff/issues/869
Added second Comment button and made it look like the other buttons in this area.
Made this happen when there are more than 10 comments but open to suggestions!
> Show second comment button when many comments on a post

- app/assets/stylesheets/overrides.sass
- app/controllers/members_controller.rb
- app/views/harvests/_card.html.haml
- app/views/members/_avatar.html.haml
- app/views/members/_gardens.html.haml
- app/views/members/_harvests.html.haml
- app/views/members/_map.html.haml
- app/views/members/_stats.html.haml
- app/views/members/show.html.haml
- spec/features/member_profile_spec.rb
Improves this issue and adds harvests to profiles: https://github.com/Growstuff/growstuff/issues/516
I went ahead and refreshed the profile page on this one to make it look more modern and less messy. I'm definitely open to any suggestions, and also ok with reverting it back to something similar to the current profile page and just improving gardens!
There was also a style bug on the harvests card with the notes field that I fixed.
Before:
After:
> Profile garden display improvements

- CONTRIBUTORS.md
- app/controllers/harvests_controller.rb
- app/views/harvests/index.html.haml
- app/views/harvests/index.rss.haml
- spec/views/harvests/index.rss.haml_spec.rb
This should solve issue #565.
Your feedback is welcome. 
Files modified:
* __harvests_controller__ - so the controller can respond to rss requests.
* __view/harvests/index.html.haml__ - modified the links on this index page to access the RSS feeds (both for an individual owner or all members.
* __view/harvests/index.rss.haml__ - created this file to handle the RSS feed requests. I based it on the previous RSS feeds for plantings and seedings but changed it based on the db table harvests.
* __spec/views/harvests/index.rss.haml_spec.rb__ - created an rspec file to assist in testing which was based on the plantings rspec file.
I tested it on a browser feed-burner, and I did struggle with the tests. I know how important they are.
> Issue 565 create harvests RSS

- CONTRIBUTORS.md
- app/views/crops/_hierarchy.html.haml
Hides the crop varieties that have not been approved. Issue #1631
- prevents the list item from displaying in the crop-hierarchy if the crop has not been approved
- adds the 'hide' class if the crop has not been approved
/cc @Br3nda
> hides crop varieties that have not been approved

- app.json
Based on @eoinkelly's work in https://github.com/ODNZSL/nzsl-online/pull/480
The version of the heroku stack is old on both staging and prod. Prod uses cedar-14 and staging uses heroku-16
by moving this into heroku's `app.json` file, we will be able to both upgrade it from a PR, and also keep staging and prod in sync.
This also adds enough info for someone else to quickly deploy their own version of growstuff.org on heroku if they want to.
> Upgrade heroku stack

- db/schema.rb
Travis isn't deploying to staging - instead, it has an error about the schema file changing.
The error Travis-CI during deploy is:
```
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git checkout -- <file>..." to discard changes in working directory)
modified:   db/schema.rb
```
I've re-run migrate, and the schema version format has changed in Rails 5.2. Here's the modified file needed.
> Fix modified schema deploy error

- app/resources/api/v1/planting_resource.rb
- spec/controllers/api/v1/plantings_controller_spec.rb
- spec/requests/api/v1/plantings_request_spec.rb
I'm made a component to pull growstuff data into my home automation system (home assistant, nifty and open source) so i can see it side by side with the plant moisture system, and the irrigation
I needed to add some attributes and filters to the api resources to get the data i needed.
> Adding more attributes and filters to the api

- spec/controllers/api/v1/plantings_controller_spec.rb
Auto corrected by following Lint Ruby EmptyLine
Click [here](https://awesomecode.io/repos/Growstuff/growstuff/ruby_config_groups/527) to configure it on awesomecode.io
> Auto corrected by following Lint Ruby EmptyLine

- README.md
Waffle is shutting down. The existing stories have been migrated to github projects.
closes #1877
> Remove waffle link, replace with github projects

- Gemfile
- Gemfile.lock
Production and staging have "Wrong version" errors when attempting SSL connection to bonsai elastic search. I've rolled production back one version on heroku to fix.
This should fix the error - not sure as i can't reproduce it on dev. We'll know once we test on staging.
> Pin elasticsearch back at 6, to fix errors on staging/prod

- db/migrate/20190720000625_notifications_to_mailboxer.rb
can't use the method on notification model during migration, because if a user has opted out of notifications then the method returns nil.
instead, send messages for everyone
note: email sending is turned off while this migration runs
> [HOTFIX] Send message to everyone in migration (no email tho)

- CONTRIBUTORS.md
- spec/controllers/photos_controller_spec.rb
Based on the currently opened issue: https://github.com/Growstuff/growstuff/issues/2332 this should be the fix to the warning.
When running the tests, error no longer appears.
> Use specific error for raise_error expectation in specs (GH-2332)

- app/views/gardens/_form.html.haml
A while ago, garden type was made optional for the garden (https://github.com/Growstuff/growstuff/commit/55f6636da54314e0a000dd661d2a664f6b1d506b) but the edit form would always enforce a `garden_type_id` - this change includes a blank option so that when updating a garden - `garden_type_id` can be set to `nil`. (For more context see: https://github.com/Growstuff/growstuff/issues/2361)
No automated tests has been added since the current GardenController tests already account for `garden_type_id` being `nil` (https://github.com/Growstuff/growstuff/blob/8360e4ac0f5aaaf6a5a56a3235894fc591a846c3/spec/controllers/gardens_controller_spec.rb#L41 - https://github.com/Growstuff/growstuff/blob/8360e4ac0f5aaaf6a5a56a3235894fc591a846c3/spec/controllers/gardens_controller_spec.rb#L7)
I could add a …
> GH-2361 Optional garden type when editing garden

- app/views/gardens/show.html.haml
- spec/features/gardens/gardens_spec.rb
Garden show does not display garden type, this PR adds that functionality.
I placed it in `About this garden section`
Original issue: https://github.com/Growstuff/growstuff/issues/2362
I found somewhere in the docs that the feature tests are preferred over the view tests so I added a new one for the garden type and changed the description of the file to make it more descriptive. 
Also, I changed the `unless blank?` to `if present?` for better readability, I can also remove that commit if you so prefer. (https://github.com/Growstuff/growstuff/commit/fbb1be31688c5f28007e3f77cecfd44b4cb8409e)
> GH-2362 Display garden type on garden show

- app/controllers/gardens_controller.rb
- app/views/gardens/index.html.haml
Gardens index page needs some love and this is an attempt of it. 
Following changes were made: 
- page navigation is no longer stretched cross page - I followed existing designs done in plantings and crops index
- jump to is shown only when viewing own gardens
- name of the garden does not have green background
- no perennial plantings is shown if none of the items in category exist
- plantings are shown next to the image instead of below
- I tested it by clicking around - looks good
- I also checked how it looks on mobile - and there is this issue of not being stretched cross screen, but after visiting for example plantings index page and going back to gardens - the content is shown correctly - not sure why that happens, let me know if you know what the deal is there...
Here are some …
> GH-2369 update gardens index style

- app/models/concerns/search_photos.rb
- app/models/photo.rb
- app/views/photos/_card.html.haml
links to photo owner is a broken link whenever the login_name doesn't match the slug.
e.g. when the user has upper case in their login name
> BUGFIX: member slug needed on photos, to make link

- spec/requests/conversations_spec.rb
Auto corrected by following Lint Ruby RSpec/NotToNot
Click [here](https://awesomecode.io//repos/Growstuff/growstuff/lint_configs/ruby/28129) to configure it on awesomecode.io
> Auto corrected by following Lint Ruby RSpec/NotToNot

- spec/models/crop_spec.rb
Auto corrected by following Lint Ruby RSpec/ExampleWording
Click [here](https://awesomecode.io//repos/Growstuff/growstuff/lint_configs/ruby/27199) to configure it on awesomecode.io
> Auto corrected by following Lint Ruby RSpec/ExampleWording

- config/initializers/devise.rb
Auto corrected by following Lint Ruby Lint/RedundantCopEnableDirective
Click [here](https://awesomecode.io//repos/Growstuff/growstuff/lint_configs/ruby/9286) to configure it on awesomecode.io
> Auto corrected by following Lint Ruby Lint/RedundantCopEnableDirective

- config/initializers/devise.rb
Auto corrected by following Lint Ruby Layout/EmptyLineAfterMagicComment
Click [here](https://awesomecode.io//repos/Growstuff/growstuff/lint_configs/ruby/1746) to configure it on awesomecode.io
> Auto corrected by following Lint Ruby Layout/EmptyLineAfterMagicComment
